// Ligas is loaded only when opened. All competition mutations are server RPCs.
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const states={active:'En curso',registration:'Inscripciones abiertas',groups:'Fase de grupos',groups_done:'Grupos terminados',knockout:'Eliminatorias',completed:'Finalizada',cancelled:'Cancelada'};
const num=v=>Number(v)||0;
const round=n=>n===2?'Final':n===4?'Semifinales':n===8?'Cuartos de final':n===16?'Octavos de final':`Ronda de ${n}`;
const points=g=>g.group_no?1:g.round_size===2?5:g.round_size===4?3:2;
const dateText=(s,tz)=>new Intl.DateTimeFormat('es-UY',{dateStyle:'medium',timeStyle:'short',timeZone:tz}).format(new Date(s));
const button=(action,label,attrs='')=>`<button type="button" data-lg-action="${action}" ${attrs}>${label}</button>`;
const badge=s=>`<span class="lg105-badge">${esc(states[s]||s)}</span>`;
const localInput=iso=>{const d=new Date(iso);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
const userName=e=>e?.name||'Sin rival';
function avatar(e){let url='';try{const u=new URL(e?.profile_photo_url);if(u.protocol==='https:')url=u.href}catch{}return url?`<img class="lg105-avatar" src="${esc(url)}" alt="" loading="lazy">`:`<span class="lg105-avatar">${esc(userName(e).slice(0,2).toUpperCase())}</span>`}
export function createLeaguesUI({supabase,getUser,searchPlayers,onRP}){
 const root=document.getElementById('leaguesRootV105');
 let lid=null,did=null,league=null,detail=null,generation=0,busy=false,dialog=null,user=null;
 const rpc=async(name,args)=>{const {data,error}=await supabase.rpc(name,args);if(error)throw error;return data};
 const message=error=>/PGRST202|does not exist|schema cache/.test(`${error.code} ${error.message}`)?'Ligas todavía no está activada en la base de datos. El administrador debe ejecutar la migración 1.0.5.':error.message||'No se pudo completar la acción. Probá de nuevo.';
 function errorBox(error){const box=root.querySelector('[data-lg-error]');if(box){box.textContent=message(error);box.hidden=false}}
 function shell(content){root.innerHTML=`<div class="lg105-top"><div><small>CIRCUITOS · INDIVIDUAL</small><h1>Ligas</h1><p>Torneos por fechas. Una clasificación que sigue creciendo.</p></div><div class="lg105-actions">${button('list','Todas las ligas')}${button('refresh','Actualizar')}${button('create','＋ Crear liga','class="lg105-primary"')}</div></div><p data-lg-error role="alert" hidden></p>${content}`}
 function rules(){return `<details class="lg105-card lg105-rules"><summary>Reglamento y puntuación</summary><p>Victorias: grupos <b>1 punto</b> · eliminatorias anteriores a semifinales <b>2</b> · semifinal <b>3</b> · final <b>5</b>. Se suman todas las fechas.</p><p>Clasifican los dos mejores disponibles de cada grupo. Desempate de grupos: victorias, diferencia de sets, diferencia de tantos y orden aleatorio fijado al inscribirse. General: puntos, títulos de fecha, victorias jugadas, diferencia de sets y tantos; si persiste, se comparte posición.</p><p>Inicialmente hay hasta 4 jugadores por grupo. Las altas tardías se sortean entre los grupos más pequeños, sin mover jugadores, y pueden superar 4. Se cierran cuando termina el último partido de grupos.</p><p>“No participa” otorga los puntos de la fase al rival, pero no RP. Pase libre y doble ausencia no dan puntos. PJ, G, P y sets cuentan únicamente partidos jugados. Los resultados confirmados son definitivos: revisalos antes de guardar.</p><p>Los partidos jugados actualizan el RP individual global. Las ligas son visibles para usuarios registrados. El anfitrión administra participantes y resultados.</p></details>`}
 function table(rows,{groups=false}={}){return `<div class="lg105-scroll" tabindex="0" aria-label="Tabla de clasificación"><table><thead><tr><th>#</th><th>Jugador</th>${groups?'':'<th title="Fechas disputadas">Fechas</th>'}<th title="Partidos jugados">PJ</th><th>G</th><th>P</th><th title="Sets a favor">SF</th><th title="Sets en contra">SC</th><th title="Diferencia de sets">DS</th><th>${groups?'Vict.':'Pts'}</th></tr></thead><tbody>${rows.map((e,i)=>`<tr><td>${num(groups?e.group_position:e.position)||i+1}</td><td><div class="lg105-person">${avatar(e)}<span>${esc(userName(e))}${e.withdrawn?'<small>Retirado de esta fecha</small>':''}</span></div></td>${groups?'':`<td>${num(e.dates)}</td>`}<td>${num(e.played)}</td><td>${num(e.wins)}</td><td>${num(e.losses)}</td><td>${num(e.sets_for)}</td><td>${num(e.sets_against)}</td><td>${num(e.sets_for)-num(e.sets_against)}</td><td><strong>${num(groups?e.group_wins:e.score)}</strong></td></tr>`).join('')||'<tr><td colspan="10">Todavía no hay participantes.</td></tr>'}</tbody></table></div>`}
 function renderList(rows){shell(`<div class="lg105-grid">${rows.map(l=>`<article class="lg105-card"><div class="lg105-between">${badge(l.status)}<small>${l.is_owner?'Sos anfitrión':l.following?'Seguís esta liga':''}</small></div><h2>${esc(l.name)}</h2><p>${l.frequency==='weekly'?'Semanal':'Mensual'} · ${l.date_count} fechas · ${l.finished_dates} finalizadas</p>${button('league','Ver liga',`data-id="${l.id}" class="lg105-primary"`)}</article>`).join('')||'<article class="lg105-card"><h2>La primera liga empieza con vos</h2><p>Creá un circuito y sumá jugadores a cada fecha.</p></article>'}</div>${rules()}`)}
 function renderLeague(data){const l=data.league;league=data;
 shell(`<article class="lg105-card"><div class="lg105-between"><h2>${esc(l.name)}</h2>${badge(l.status)}</div><p>${esc(l.description)}</p><p>${l.frequency==='weekly'?'Semanal':'Mensual'} · ${l.date_count} fechas · Sorteo ${l.draw_mode==='balanced'?'equilibrado por RP':'aleatorio'} · Al mejor de ${l.best_of} sets</p><div class="lg105-actions">${button('follow',data.reminders?'Silenciar recordatorios':'Recibir recordatorios',`data-enabled="${!data.reminders}"`)}${data.is_owner&&l.status==='active'&&data.dates.every(d=>['completed','cancelled'].includes(d.status))?button('finish_league','Cerrar liga y consagrar clasificación'):''}</div><small>Recordatorios a 7 días, 1 día y 1 hora. Para recibirlos fuera de la app, activá las notificaciones del dispositivo en Configuración.</small></article><section class="lg105-card"><h2>Clasificación general</h2>${table(data.standings)}<small>Se suman todas las fechas. Puntos por incomparecencia incluidos; partidos no jugados excluidos de PJ y sets.</small></section><h2>Calendario y archivo</h2><div class="lg105-grid">${data.dates.map(d=>`<article class="lg105-card"><div class="lg105-between"><h3>Fecha ${d.date_no}</h3>${badge(d.status)}</div><p>${esc(dateText(d.starts_at,l.timezone))}</p><p>${esc(d.venue||'Lugar por confirmar')} · ${d.entries} inscritos</p>${button('date',d.status==='completed'?'Ver resultados':'Abrir fecha',`data-id="${d.id}"`)}</article>`).join('')}</div>${rules()}<details class="lg105-card"><summary>Registro de cambios</summary>${data.audit.map(a=>`<p>${esc(dateText(a.created_at,l.timezone))} · ${esc(({create:'Liga creada',add:'Jugador añadido',join:'Inscripción',draw:'Sorteo de grupos',score:'Resultado confirmado',walkover:'No participa',withdraw:'Retiro',knockout:'Eliminatorias generadas',reschedule:'Fecha reprogramada',remove:'Inscripción quitada',leave:'Baja de inscripción',void:'Doble ausencia',finish_league:'Liga cerrada',cancel_date:'Fecha cancelada'})[a.action]||a.action)} ${a.details.reason?`— ${esc(a.details.reason)}`:''}</p>`).join('')}</details>`)}
 function groupRows(entries,games){return entries.map(e=>{const gg=games.filter(g=>g.group_no&&[g.player1,g.player2].includes(e.entry_id));const pp=gg.filter(g=>g.status==='played');return {...e,played:pp.length,wins:pp.filter(g=>g.winner===e.entry_id).length,losses:pp.filter(g=>g.winner!==e.entry_id).length,group_wins:gg.filter(g=>['played','walkover'].includes(g.status)&&g.winner===e.entry_id).length,sets_for:pp.reduce((s,g)=>s+(g.player1===e.entry_id?g.sets1:g.sets2),0),sets_against:pp.reduce((s,g)=>s+(g.player1===e.entry_id?g.sets2:g.sets1),0),pd:pp.reduce((s,g)=>s+(g.player1===e.entry_id?g.points1-g.points2:g.points2-g.points1),0)}}).sort((a,b)=>b.group_wins-a.group_wins||(b.sets_for-b.sets_against)-(a.sets_for-a.sets_against)||b.pd-a.pd||a.tie_order.localeCompare(b.tie_order)).map((e,i)=>({...e,group_position:i+1}))}
 function gameCard(g,byId,owner){const resolved=g.status!=='pending';return `<article class="lg105-game"><small>${g.group_no?'Grupo '+g.group_no:round(g.round_size)} · ${points(g)} ${points(g)===1?'punto':'puntos'} por victoria</small><div class="lg105-match"><span class="${g.winner===g.player1?'lg105-winner':''}">${esc(userName(byId.get(g.player1)))}</span><b>${g.status==='played'?g.sets1+' – '+g.sets2:'vs'}</b><span class="${g.winner===g.player2?'lg105-winner':''}">${esc(userName(byId.get(g.player2)))}</span></div>${g.status==='played'?`<small>${g.sets.map(s=>s.join('–')).join(' · ')} · RP ${g.rp1>0?'+':''}${g.rp1} / ${g.rp2>0?'+':''}${g.rp2}</small>`:`<small>${({pending:'Pendiente',bye:'Pase libre · sin puntos ni RP',walkover:'No participa · sin RP',void:'Sin participantes · sin puntos'})[g.status]}</small>`}${owner&&!resolved?`<div class="lg105-actions">${button('score','Cargar resultado',`data-id="${g.id}"`)}${button('absence','No participa',`data-id="${g.id}"`)}</div>`:''}</article>`}
 function renderDate(data){detail=data;const d=data.date,l=data.league,owner=data.is_owner&&l.status==='active',byId=new Map(data.entries.map(e=>[e.entry_id,e]));const me=data.entries.find(e=>e.user_id===getUser()?.id);const open=['registration','groups'].includes(d.status)&&l.status==='active';
 const groups=Object.entries(data.entries.reduce((acc,e)=>{if(e.group_no)(acc[e.group_no]??=[]).push(e);return acc},{}));const ko=[...new Set(data.games.filter(g=>g.round_size).map(g=>g.round_size))].sort((a,b)=>b-a);
 shell(`${button('league','← '+esc(l.name),`data-id="${l.id}"`)}<article class="lg105-card"><div class="lg105-between"><h2>Fecha ${d.date_no}</h2>${badge(d.status)}</div><p>${esc(dateText(d.starts_at,l.timezone))} · ${esc(d.venue||'Lugar por confirmar')}</p><p>${data.entries.length} inscritos${d.champion_id?' · Campeón: '+esc(userName(byId.get(d.champion_id))):''}</p><div class="lg105-actions">${open&&!me?button('join','Inscribirme','class="lg105-primary"'):''}${me&&d.status==='registration'?button('leave','Quitar mi inscripción'):''}${owner&&open?button('add','Añadir jugadores'):''}${owner&&d.status==='registration'?button('draw','Sortear grupos','class="lg105-primary"'):''}${owner&&d.status==='groups_done'?button('knockout','Generar eliminatorias','class="lg105-primary"'):''}${owner&&open?button('reschedule','Cambiar horario o lugar'):''}${owner&&d.status==='registration'?button('cancel_date','Cancelar fecha'):''}</div>${d.status==='groups'?'<p>Se admiten altas mientras quede algún partido pendiente de grupos. No se repetirá el sorteo.</p>':''}</article><details class="lg105-card" ${d.status==='registration'?'open':''}><summary>Participantes (${data.entries.length})</summary>${data.entries.map(e=>`<div class="lg105-between lg105-entry"><div class="lg105-person">${avatar(e)}<span>${esc(e.name)}${e.group_no?` · Grupo ${e.group_no}`:''}${e.withdrawn?' · Retirado':''}</span></div>${owner&&d.status==='registration'?button('remove','Quitar',`data-user="${esc(e.user_id)}"`):owner&&!e.withdrawn&&['groups','groups_done','knockout'].includes(d.status)?button('withdraw','Retirar',`data-id="${e.entry_id}"`):''}</div>`).join('')||'<p>No hay inscritos todavía.</p>'}</details>${groups.map(([n,entries])=>`<section class="lg105-card"><h2>Grupo ${n}</h2>${table(groupRows(entries,data.games),{groups:true})}<div class="lg105-grid">${data.games.filter(g=>g.group_no===Number(n)).map(g=>gameCard(g,byId,owner)).join('')}</div></section>`).join('')}${ko.length?`<h2>Eliminatorias</h2><div class="lg105-bracket">${ko.map(n=>`<section class="lg105-round"><h3>${round(n)}</h3>${data.games.filter(g=>g.round_size===n).map(g=>gameCard(g,byId,owner)).join('')}</section>`).join('')}</div>`:''}<section class="lg105-card"><h2>Puntos de esta fecha</h2>${table([...data.entries].sort((a,b)=>b.score-a.score).map(e=>({...e,dates:d.status==='registration'?0:1})))}<p>${data.entries.map(e=>e.walkovers?`${esc(e.name)}: ${e.walkovers} victoria(s) por incomparecencia.`:'').filter(Boolean).join(' ')}</p></section>${rules()}`)}
 async function load({leagueId=lid,dateId=did,quiet=false}={}){if(!root)return;const current=getUser()?.id;if(!current){shell('<p>Iniciá sesión para ver las ligas.</p>');return}if(user&&user!==current){leagueId=null;dateId=null;closeDialog()}user=current;lid=leagueId;did=dateId;const token=++generation;if(!quiet)shell('<p role="status">Cargando ligas…</p>');try{const data=await rpc(did?'get_league_date_v105':lid?'get_league_v105':'get_leagues_v105',did?{p_date:did}:lid?{p_league:lid}:{});if(token!==generation||current!==getUser()?.id)return;if(did){lid=data.league.id;renderDate(data)}else if(lid)renderLeague(data);else renderList(data)}catch(e){if(token===generation)errorBox(e)}}
 function closeDialog(){if(dialog){dialog.close();dialog.remove();dialog=null}}
 function modal(title,body,submit){closeDialog();dialog=document.createElement('dialog');dialog.className='lg105-dialog';dialog.setAttribute('aria-label',title);dialog.innerHTML=`<form><div class="lg105-between"><h2>${esc(title)}</h2><button type="button" data-close aria-label="Cerrar">✕</button></div>${body}<p role="alert" data-form-error></p><div class="lg105-actions"><button type="button" data-close>Cancelar</button><button type="submit" class="lg105-primary">Confirmar</button></div></form>`;document.body.append(dialog);const el=dialog;el.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeDialog);el.addEventListener('cancel',e=>{if(busy)e.preventDefault()});el.querySelector('form').onsubmit=async e=>{e.preventDefault();if(busy)return;const data=new FormData(e.target);busy=true;el.querySelectorAll('button').forEach(b=>b.disabled=true);try{await submit(data,el);closeDialog();await load()}catch(err){el.querySelector('[data-form-error]').textContent=message(err)}finally{busy=false;if(el.isConnected)el.querySelectorAll('button').forEach(b=>b.disabled=false)}};el.showModal();return el}
 async function mutate(action,payload={}){const result=await rpc('league_command_v105',{p_action:action,p_payload:{league_id:lid,date_id:did,...payload}});if(action==='create'){lid=result.league_id;did=null}if(action==='score')onRP?.();return result}
 const confirm=(title,body,action,payload={})=>modal(title,`<p>${body}</p>`,()=>mutate(action,payload));
 const field=(label,name,type='text',attrs='')=>`<label>${label}<input name="${name}" type="${type}" ${attrs}></label>`;
 root.addEventListener('click',async ev=>{const b=ev.target.closest('[data-lg-action]');if(!b||busy)return;const action=b.dataset.lgAction;
  if(action==='list')return load({leagueId:null,dateId:null});if(action==='league')return load({leagueId:num(b.dataset.id),dateId:null});if(action==='date')return load({dateId:num(b.dataset.id)});if(action==='refresh')return load();
  if(action==='create'){const tomorrow=new Date(Date.now()+86400000);return modal('Crear liga',`${field('Nombre','name','text','required minlength="3" maxlength="80"')}<label>Descripción<textarea name="description" maxlength="1000"></textarea></label><div class="lg105-form-grid"><label>Frecuencia<select name="frequency"><option value="weekly">Semanal</option><option value="monthly">Mensual</option></select></label>${field('Cantidad de fechas (semanas o meses)','date_count','number','required min="1" max="60" value="6"')}${field('Primera fecha y hora','starts_at','datetime-local',`required value="${localInput(tomorrow)}"`)}<label>Sorteo<select name="draw_mode"><option value="random">Aleatorio</option><option value="balanced">Equilibrado por RP</option></select></label><label>Partidos<select name="best_of"><option value="5">Al mejor de 5 sets</option><option value="3">Al mejor de 3 sets</option></select></label></div>${field('Lugar','venue','text','maxlength="180"')}<p>Zona horaria: ${esc(Intl.DateTimeFormat().resolvedOptions().timeZone)}. Se conserva el día y la hora; si un mes no tiene ese día, se usa su último día.</p><p>La lista de jugadores se elige en cada fecha, después de crear la liga.</p>`,f=>mutate('create',{...Object.fromEntries(f),date_count:num(f.get('date_count')),best_of:num(f.get('best_of')),starts_at:new Date(f.get('starts_at')).toISOString(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone}))}
  if(action==='follow'){busy=true;try{await mutate('follow',{enabled:b.dataset.enabled==='true'});await load()}catch(e){errorBox(e)}finally{busy=false}return}
  if(action==='add'){const el=modal('Añadir jugador',`<label>Buscar por nombre o usuario<input data-search type="search" placeholder="Escribí al menos 2 letras" autocomplete="off"></label><div data-results></div><input name="user_id" type="hidden" required><p data-selected>Elegí un jugador.</p>${detail.date.status==='groups'?'<p>Se sorteará entre los grupos más pequeños y jugará contra todos sus integrantes.</p>':''}`,f=>{if(!f.get('user_id'))throw Error('Elegí un jugador de la lista');return mutate('add',{user_id:f.get('user_id')})});let timer,seq=0;el.querySelector('[data-search]').oninput=e=>{clearTimeout(timer);const q=e.target.value.trim(),token=++seq;timer=setTimeout(async()=>{if(q.length<2)return;try{const rows=await searchPlayers(q,getUser().id);if(token!==seq||!el.isConnected)return;const box=el.querySelector('[data-results]');box.innerHTML=rows.filter(p=>!detail.entries.some(e=>e.user_id===p.id)).map(p=>`<button type="button" data-player="${esc(p.id)}">${esc([p.first_name,p.last_name].filter(Boolean).join(' ')||p.username)} · @${esc(p.username)}</button>`).join('')||'<p>No se encontraron jugadores disponibles.</p>';box.querySelectorAll('[data-player]').forEach(btn=>btn.onclick=()=>{el.querySelector('[name=user_id]').value=btn.dataset.player;el.querySelector('[data-selected]').textContent='Seleccionado: '+btn.textContent})}catch(e){el.querySelector('[data-form-error]').textContent=message(e)}},300)};return}
  if(action==='reschedule')return modal('Reprogramar fecha',`${field('Nueva fecha y hora (zona horaria de este dispositivo)','starts_at','datetime-local',`required value="${localInput(detail.date.starts_at)}"`)}${field('Lugar','venue','text',`maxlength="180" value="${esc(detail.date.venue)}"`)}<p>Se avisará a quienes siguen la liga y se actualizarán los recordatorios.</p>`,f=>mutate(action,{starts_at:new Date(f.get('starts_at')).toISOString(),venue:f.get('venue')}));
  if(action==='score'){const g=detail.games.find(g=>g.id===num(b.dataset.id)),e=id=>detail.entries.find(e=>e.entry_id===id);return modal('Cargar resultado',`<p>${esc(userName(e(g.player1)))} (izquierda) vs ${esc(userName(e(g.player2)))} (derecha)</p>${Array.from({length:detail.league.best_of},(_,i)=>`<div class="lg105-set"><span>Set ${i+1}</span><input aria-label="Set ${i+1}, ${esc(userName(e(g.player1)))}" name="a${i}" type="number" min="0" max="999" placeholder="—"><input aria-label="Set ${i+1}, ${esc(userName(e(g.player2)))}" name="b${i}" type="number" min="0" max="999" placeholder="—"></div>`).join('')}<p>Dejá vacíos los sets no jugados. Este resultado será definitivo y actualizará el RP global.</p><label class="lg105-check"><input type="checkbox" required> Revisé los jugadores y todos los sets.</label>`,f=>{const sets=[];let blank=false;for(let i=0;i<detail.league.best_of;i++){const a=f.get('a'+i),b=f.get('b'+i);if(a===''&&b===''){blank=true;continue}if(a===''||b===''||blank)throw Error('Completá ambos puntos de cada set, sin saltar sets');sets.push([Number(a),Number(b)])}return mutate('score',{game_id:g.id,sets})})}
  if(action==='absence'){const g=detail.games.find(g=>g.id===num(b.dataset.id));return modal('No participa',`<label>Ausencia<select name="absent_id">${[g.player1,g.player2].map(id=>`<option value="${id}">${esc(userName(detail.entries.find(e=>e.entry_id===id)))}</option>`).join('')}<option value="both">No participa ninguno</option></select></label>${field('Motivo','reason','text','required minlength="3" maxlength="300"')}<p>El rival recibe ${points(g)} puntos de liga. No se modifica el RP. Si faltan ambos, no se otorgan puntos.</p>`,f=>mutate(f.get('absent_id')==='both'?'void':'walkover',{game_id:g.id,absent_id:f.get('absent_id')==='both'?null:num(f.get('absent_id')),reason:f.get('reason')}))}
  if(action==='withdraw')return modal('Retirar de esta fecha',`${field('Motivo','reason','text','required minlength="3" maxlength="300"')}<p>Se conservan los resultados jugados. Los encuentros pendientes se resuelven por incomparecencia; no se genera RP por ellos.</p>`,f=>mutate('withdraw',{entry_id:num(b.dataset.id),reason:f.get('reason')}));
  const confirmations={join:['Inscribirme','Te sumás a esta fecha y a los recordatorios de la liga. Si los grupos ya están sorteados, tu grupo se asignará automáticamente.'],leave:['Quitar inscripción','Podés volver a inscribirte mientras la fase de grupos siga abierta.'],remove:['Quitar jugador','Se quitará esta inscripción. No afecta otras fechas.'],draw:['Sortear grupos','Se formarán grupos de hasta 4. El sorteo no puede repetirse. Después, las altas tardías solo se repartirán entre los grupos existentes.'],knockout:['Generar eliminatorias','Se clasificarán los dos mejores disponibles por grupo. Los pases libres no otorgan puntos.'],finish_league:['Cerrar liga','La clasificación general quedará consagrada con la suma de todas las fechas.'],cancel_date:['Cancelar fecha','Esta fecha quedará cancelada. No se podrá jugar ni inscribir participantes.']};
  if(confirmations[action])return confirm(...confirmations[action],action,action==='remove'?{user_id:b.dataset.user}:{});
 });
 // No polling on other tabs or while the application is in the background.
 setInterval(()=>{if(root.closest('.tab-page')?.classList.contains('active')&&!document.hidden&&!busy&&!dialog?.open)load({quiet:true})},30000);
 return {open:load};
}
