-- TT Rivals 1.0.1 — P7.4R.4.1 Integridad 3 de 10
-- Regla: dentro de un mismo día (Uruguay), 3 partidos de menos de 60 s
-- entre los últimos 10 activan una retención preventiva.
-- Se instala en SIMULACIÓN. No aplica sanciones reales hasta que el Admin active el motor.

begin;

do $preflight$
begin
  if to_regclass('public.auto_moderation_signals_v77') is null
     or to_regclass('public.auto_moderation_cases_v77') is null
     or to_regclass('tt_private_v77.auto_moderation_config_v77') is null then
    raise exception 'Falta P7.4R.4: instalá primero la moderación automática base';
  end if;
  if to_regprocedure('public.confirm_match_result(bigint)') is null then
    raise exception 'No se encontró public.confirm_match_result(bigint). No se modificó la confirmación';
  end if;
end;
$preflight$;

alter table tt_private_v77.auto_moderation_config_v77
  add column if not exists short_match_seconds integer not null default 60,
  add column if not exists short_matches_required integer not null default 3,
  add column if not exists recent_matches_limit integer not null default 10,
  add column if not exists evaluation_timezone text not null default 'America/Montevideo';

-- Toda instalación o actualización vuelve deliberadamente a simulación.
update tt_private_v77.auto_moderation_config_v77
set mode='observe',
    lookback_days=7,
    short_match_seconds=60,
    short_matches_required=3,
    recent_matches_limit=10,
    evaluation_timezone='America/Montevideo',
    updated_at=now()
where singleton=true;

-- Las señales anteriores (pareja repetida, instalación y ráfaga) dejan de decidir.
update public.auto_moderation_signals_v77
set active=false
where active and signal_type<>'duration_extreme';

update public.auto_moderation_cases_v77
set status='cleared',score=0,distinct_matches=0,distinct_signal_types=0,
    evidence='[]'::jsonb,updated_at=now()
where status in('observed','would_suspend');

create table if not exists public.integrity_sanctions_v78(
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  trigger_match_id bigint,
  level smallint not null check(level between 1 and 3),
  casual_locked boolean not null default true,
  competitive_locked boolean not null default false,
  status text not null default 'active' check(status in('active','expired','revoked')),
  starts_at timestamptz not null default now(),
  ends_at timestamptz not null,
  reason text not null,
  evidence jsonb not null default '{}'::jsonb,
  appealed_at timestamptz,
  appeal_message text,
  reviewed_by uuid,
  reviewed_at timestamptz,
  review_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists integrity_sanctions_v78_active_user_idx
on public.integrity_sanctions_v78(user_id)
where status='active';

create index if not exists integrity_sanctions_v78_user_date_idx
on public.integrity_sanctions_v78(user_id,created_at desc);

create table if not exists public.integrity_match_holds_v78(
  match_id bigint primary key,
  participants uuid[] not null,
  triggered_users uuid[] not null,
  match_type text not null,
  hold_scope text not null check(hold_scope in('statistics','elo_and_statistics')),
  status text not null default 'pending' check(status in('pending','approved','annulled')),
  duration_seconds integer not null,
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by uuid,
  resolution_note text
);

create index if not exists integrity_match_holds_v78_status_idx
on public.integrity_match_holds_v78(status,created_at desc);

create table if not exists public.integrity_notifications_v78(
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  sanction_id bigint,
  title text not null,
  message text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists integrity_notifications_v78_user_idx
on public.integrity_notifications_v78(user_id,created_at desc);

alter table public.integrity_sanctions_v78 enable row level security;
alter table public.integrity_match_holds_v78 enable row level security;
alter table public.integrity_notifications_v78 enable row level security;
revoke all on public.integrity_sanctions_v78 from public,anon,authenticated;
revoke all on public.integrity_match_holds_v78 from public,anon,authenticated;
revoke all on public.integrity_notifications_v78 from public,anon,authenticated;

create or replace function public.tt_v78_match_occurred_at(p_doc jsonb)
returns timestamptz
language plpgsql
stable
set search_path=''
as $function$
begin
  return coalesce(
    nullif(p_doc->>'result_submitted_at','')::timestamptz,
    nullif(p_doc->>'confirmed_at','')::timestamptz,
    nullif(p_doc->>'created_at','')::timestamptz
  );
exception when others then
  return null;
end;
$function$;

create or replace function public.tt_v78_match_duration_seconds(p_doc jsonb)
returns integer
language plpgsql
stable
set search_path=''
as $function$
declare
  v_seconds numeric;
  v_started timestamptz;
  v_finished timestamptz;
begin
  v_seconds:=public.tt_v77_json_number(p_doc,'gameplay_seconds');
  if v_seconds is not null then return greatest(0,v_seconds::integer); end if;

  v_started:=coalesce(
    nullif(p_doc->>'accepted_at','')::timestamptz,
    nullif(p_doc->>'started_at','')::timestamptz,
    nullif(p_doc->>'created_at','')::timestamptz
  );
  v_finished:=coalesce(
    nullif(p_doc->>'result_submitted_at','')::timestamptz,
    nullif(p_doc->>'confirmed_at','')::timestamptz
  );
  if v_started is null or v_finished is null then return null; end if;
  return greatest(0,extract(epoch from (v_finished-v_started))::integer);
exception when others then
  return null;
end;
$function$;

create or replace function public.tt_v78_expire_sanctions()
returns void
language sql
security definer
set search_path=''
as $function$
  update public.integrity_sanctions_v78
  set status='expired',updated_at=now()
  where status='active' and ends_at<=now();
$function$;

create or replace function public.tt_v78_active_sanction(p_user_id uuid)
returns public.integrity_sanctions_v78
language plpgsql
security definer
set search_path=''
as $function$
declare v_row public.integrity_sanctions_v78%rowtype;
begin
  perform public.tt_v78_expire_sanctions();
  select * into v_row
  from public.integrity_sanctions_v78 s
  where s.user_id=p_user_id and s.status='active' and s.ends_at>now()
  order by s.created_at desc limit 1;
  return v_row;
end;
$function$;

create or replace function public.tt_v78_create_sanction(
  p_user_id uuid,
  p_match_id bigint,
  p_competitive_locked boolean,
  p_evidence jsonb
)
returns public.integrity_sanctions_v78
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_row public.integrity_sanctions_v78%rowtype;
  v_previous integer:=0;
  v_level smallint:=1;
  v_hours integer:=24;
  v_message text;
begin
  perform public.tt_v78_expire_sanctions();
  select * into v_row from public.integrity_sanctions_v78
  where user_id=p_user_id and status='active' and ends_at>now()
  order by created_at desc limit 1 for update;
  if found then return v_row; end if;

  select count(*)::integer into v_previous
  from public.integrity_sanctions_v78
  where user_id=p_user_id and status<>'revoked'
    and created_at>=now()-interval '90 days';
  v_level:=least(3,v_previous+1)::smallint;
  v_hours:=case v_level when 1 then 24 when 2 then 72 else 168 end;
  v_message:='Detectamos 3 partidos de menos de un minuto entre tus últimos 10 del día. '
    ||case when p_competitive_locked
      then 'Las partidas con Elo y los casuales oficiales quedan bloqueados temporalmente. '
      else 'Los casuales oficiales quedan bloqueados temporalmente. ' end
    ||'La sanción termina el '||to_char(now()+make_interval(hours=>v_hours),'DD/MM/YYYY HH24:MI')
    ||'. Las reincidencias son acumulables y progresivamente más extensas.';

  insert into public.integrity_sanctions_v78(
    user_id,trigger_match_id,level,casual_locked,competitive_locked,
    ends_at,reason,evidence
  ) values(
    p_user_id,p_match_id,v_level,true,p_competitive_locked,
    now()+make_interval(hours=>v_hours),
    '3 partidos de menos de 60 segundos entre los últimos 10 del día',
    coalesce(p_evidence,'{}'::jsonb)
  ) returning * into v_row;

  insert into public.integrity_notifications_v78(user_id,sanction_id,title,message)
  values(p_user_id,v_row.id,'Advertencia de integridad',v_message);
  return v_row;
end;
$function$;

-- Obtiene la mayor cantidad de partidos cortos que apareció en cualquier
-- ventana móvil de 10 partidos del usuario durante los últimos 7 días.
create or replace function public.tt_v78_best_short_window(p_user_id uuid)
returns jsonb
language sql
stable
security definer
set search_path=''
as $function$
  with config as(
    select lookback_days,short_match_seconds,recent_matches_limit,evaluation_timezone
    from tt_private_v77.auto_moderation_config_v77 where singleton=true
  ), base as(
    select
      m.id as match_id,
      lower(coalesce(to_jsonb(m)->>'match_type','ranked')) as match_type,
      public.tt_v78_match_duration_seconds(to_jsonb(m)) as duration_seconds,
      public.tt_v78_match_occurred_at(to_jsonb(m)) as occurred_at,
      timezone((select evaluation_timezone from config),public.tt_v78_match_occurred_at(to_jsonb(m)))::date as local_day
    from public.matches m,config c
    where lower(coalesce(to_jsonb(m)->>'result_status',''))='confirmed'
      and (m.player1_id=p_user_id or m.player2_id=p_user_id)
      and lower(coalesce(to_jsonb(m)->>'match_type','ranked')) in('ranked','competitive','casual')
      and public.tt_v78_match_occurred_at(to_jsonb(m))>=now()-make_interval(days=>c.lookback_days)
  ), rolling as(
    select b.*,
      count(*) filter(where b.duration_seconds<(select short_match_seconds from config))
        over(partition by b.local_day order by b.occurred_at,b.match_id
             rows between 9 preceding and current row) as short_count
    from base b
  ), best as(
    select * from rolling order by short_count desc,occurred_at desc limit 1
  ), window_rows as(
    select b.* from base b,best x
    where b.local_day=x.local_day and (b.occurred_at,b.match_id)<=(x.occurred_at,x.match_id)
    order by b.occurred_at desc,b.match_id desc
    limit (select recent_matches_limit from config)
  ), short_rows as(
    select * from window_rows
    where duration_seconds<(select short_match_seconds from config)
  )
  select jsonb_build_object(
    'short_count',coalesce((select short_count from best),0),
    'local_day',(select local_day from best),
    'competitive_involved',coalesce((select bool_or(match_type<>'casual') from short_rows),false),
    'match_types',coalesce((select jsonb_agg(distinct match_type) from short_rows),'[]'::jsonb),
    'matches',coalesce((select jsonb_agg(jsonb_build_object(
      'match_id',match_id,'match_type',match_type,'duration_seconds',duration_seconds,'occurred_at',occurred_at
    ) order by occurred_at desc) from short_rows),'[]'::jsonb)
  );
$function$;

create or replace function public.tt_v77_evaluate_user(
  p_user_id uuid,
  p_allow_enforcement boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_config tt_private_v77.auto_moderation_config_v77%rowtype;
  v_case public.auto_moderation_cases_v77%rowtype;
  v_window jsonb;
  v_short integer:=0;
  v_types integer:=0;
  v_status text:='observed';
begin
  if public.tt_v77_is_protected_user(p_user_id) then
    return jsonb_build_object('user_id',p_user_id,'protected',true,'status','ignored');
  end if;
  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text,78));
  select * into v_config from tt_private_v77.auto_moderation_config_v77 where singleton=true;
  v_window:=public.tt_v78_best_short_window(p_user_id);
  v_short:=coalesce((v_window->>'short_count')::integer,0);
  select count(*)::integer into v_types from jsonb_array_elements(coalesce(v_window->'match_types','[]'::jsonb));

  select * into v_case from public.auto_moderation_cases_v77
  where user_id=p_user_id and status in('observed','would_suspend','suspended')
  order by updated_at desc limit 1 for update;

  if exists(select 1 from public.integrity_sanctions_v78 s where s.user_id=p_user_id and s.status='active' and s.ends_at>now()) then
    v_status:='suspended';
  elsif v_short>=v_config.short_matches_required then
    v_status:='would_suspend';
  elsif v_short=0 then
    v_status:='cleared';
  end if;

  if v_status='cleared' then
    if v_case.id is not null then
      update public.auto_moderation_cases_v77
      set status='cleared',score=0,distinct_matches=0,distinct_signal_types=0,
          evidence='[]'::jsonb,evaluation_mode=v_config.mode,updated_at=now()
      where id=v_case.id;
    end if;
    return jsonb_build_object('user_id',p_user_id,'status','cleared','short_matches',0);
  end if;

  if v_case.id is null then
    insert into public.auto_moderation_cases_v77(
      user_id,status,score,distinct_matches,distinct_signal_types,evaluation_mode,evidence
    ) values(p_user_id,v_status,v_short,v_short,v_types,v_config.mode,v_window)
    returning * into v_case;
  else
    update public.auto_moderation_cases_v77
    set status=v_status,score=v_short,distinct_matches=v_short,
        distinct_signal_types=v_types,evaluation_mode=v_config.mode,
        suspension_until=(select max(s.ends_at) from public.integrity_sanctions_v78 s
          where s.user_id=p_user_id and s.status='active'),
        evidence=v_window,updated_at=now()
    where id=v_case.id returning * into v_case;
  end if;

  return jsonb_build_object(
    'case_id',v_case.id,'user_id',p_user_id,'status',v_status,
    'short_matches',v_short,'window',v_window
  );
end;
$function$;

create or replace function public.tt_v77_evaluate_match(
  p_match_id bigint,
  p_allow_enforcement boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_match public.matches%rowtype;
  v_doc jsonb;
  v_type text;
  v_occurred timestamptz;
  v_gameplay integer;
  v_limit integer:=60;
  v_mode text:='observe';
  v_player uuid;
  v_opponent uuid;
  v_results jsonb:='[]'::jsonb;
begin
  select * into v_match from public.matches m where m.id=p_match_id;
  if not found then return jsonb_build_object('ignored',true,'reason','match_not_found'); end if;
  v_doc:=to_jsonb(v_match);
  if lower(coalesce(v_doc->>'result_status',''))<>'confirmed' then
    return jsonb_build_object('ignored',true,'reason','not_confirmed');
  end if;
  if exists(select 1 from public.integrity_match_holds_v78 h where h.match_id=p_match_id and h.status='approved') then
    return jsonb_build_object('ignored',true,'reason','admin_approved');
  end if;
  v_type:=lower(coalesce(v_doc->>'match_type','ranked'));
  if v_type not in('ranked','competitive','casual') then
    return jsonb_build_object('ignored',true,'reason','unsupported_type');
  end if;
  select mode,short_match_seconds into v_mode,v_limit
  from tt_private_v77.auto_moderation_config_v77 where singleton=true;
  if v_mode='paused' then return jsonb_build_object('ignored',true,'reason','paused'); end if;

  v_occurred:=coalesce(public.tt_v78_match_occurred_at(v_doc),now());
  v_gameplay:=public.tt_v78_match_duration_seconds(v_doc);
  foreach v_player in array array[v_match.player1_id,v_match.player2_id]
  loop
    if v_player is null or public.tt_v77_is_protected_user(v_player) then continue; end if;
    v_opponent:=case when v_player=v_match.player1_id then v_match.player2_id else v_match.player1_id end;
    if v_gameplay is not null and v_gameplay<v_limit then
      perform public.tt_v77_record_signal(
        v_player,v_opponent,p_match_id,'duration_extreme',1,
        jsonb_build_object('gameplay_seconds',v_gameplay,'match_type',v_type,'rule','3_short_in_last_10_day'),
        v_occurred
      );
    end if;
    v_results:=v_results||jsonb_build_array(public.tt_v77_evaluate_user(v_player,false));
  end loop;
  return jsonb_build_object('match_id',p_match_id,'duration_seconds',v_gameplay,'evaluations',v_results);
exception when others then
  raise warning 'TT V78 no pudo evaluar partido %: %',p_match_id,sqlerrm;
  return jsonb_build_object('match_id',p_match_id,'error',sqlerrm);
end;
$function$;

-- Puerta atómica: en modo activo, el tercer partido corto queda retenido antes
-- de que confirm_match_result aplique Elo o estadísticas.
create or replace function public.confirm_match_result_integrity_v78(p_match_id bigint)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_match public.matches%rowtype;
  v_doc jsonb;
  v_user uuid:=auth.uid();
  v_type text;
  v_mode text;
  v_limit integer;
  v_duration integer;
  v_occurred timestamptz;
  v_day date;
  v_player uuid;
  v_opponent uuid;
  v_previous_short integer:=0;
  v_competitive_involved boolean:=false;
  v_player_competitive boolean:=false;
  v_triggered uuid[]:='{}'::uuid[];
  v_participants uuid[];
  v_sanction public.integrity_sanctions_v78%rowtype;
  v_existing public.integrity_sanctions_v78%rowtype;
begin
  if v_user is null then raise exception 'Sesión requerida'; end if;
  select * into v_match from public.matches where id=p_match_id for update;
  if not found then raise exception 'Partido no encontrado'; end if;
  if v_user not in(v_match.player1_id,v_match.player2_id) then raise exception 'No participás en este partido'; end if;
  v_doc:=to_jsonb(v_match);
  v_type:=lower(coalesce(v_doc->>'match_type','ranked'));
  v_participants:=array[v_match.player1_id,v_match.player2_id];

  select * into v_existing from public.tt_v78_active_sanction(v_user);
  if v_existing.id is not null and (
    (v_type='casual' and v_existing.casual_locked)
    or (v_type<>'casual' and v_existing.competitive_locked)
  ) then
    return jsonb_build_object(
      'integrity_locked',true,'sanction_id',v_existing.id,'ends_at',v_existing.ends_at,
      'message','Esta modalidad está bloqueada temporalmente por una sanción de integridad.'
    );
  end if;

  select mode,short_match_seconds into v_mode,v_limit
  from tt_private_v77.auto_moderation_config_v77 where singleton=true;
  v_duration:=public.tt_v78_match_duration_seconds(v_doc);
  v_occurred:=coalesce(public.tt_v78_match_occurred_at(v_doc),now());
  v_day:=timezone('America/Montevideo',v_occurred)::date;

  if v_mode='enforce' and v_duration is not null and v_duration<v_limit then
    foreach v_player in array v_participants loop
      if public.tt_v77_is_protected_user(v_player) then continue; end if;
      v_opponent:=case when v_player=v_match.player1_id then v_match.player2_id else v_match.player1_id end;
      select
        count(*) filter(where src.duration_seconds<v_limit)::integer,
        coalesce(bool_or(src.duration_seconds<v_limit and src.match_type<>'casual'),false)
      into v_previous_short,v_player_competitive
      from(
        select
          lower(coalesce(to_jsonb(m)->>'match_type','ranked')) as match_type,
          public.tt_v78_match_duration_seconds(to_jsonb(m)) as duration_seconds
        from public.matches m
        where lower(coalesce(to_jsonb(m)->>'result_status',''))='confirmed'
          and (m.player1_id=v_player or m.player2_id=v_player)
          and timezone('America/Montevideo',public.tt_v78_match_occurred_at(to_jsonb(m)))::date=v_day
        order by public.tt_v78_match_occurred_at(to_jsonb(m)) desc,m.id desc
        limit 9
      ) src;

      perform public.tt_v77_record_signal(
        v_player,v_opponent,p_match_id,'duration_extreme',1,
        jsonb_build_object('gameplay_seconds',v_duration,'match_type',v_type,'candidate_hold',true),v_occurred
      );
      if v_previous_short>=2 then v_triggered:=array_append(v_triggered,v_player); end if;
      v_competitive_involved:=v_competitive_involved or v_player_competitive or v_type<>'casual';
    end loop;
  end if;

  if cardinality(v_triggered)>0 then
    insert into public.integrity_match_holds_v78(
      match_id,participants,triggered_users,match_type,hold_scope,duration_seconds,evidence
    ) values(
      p_match_id,v_participants,v_triggered,v_type,
      case when v_type='casual' then 'statistics' else 'elo_and_statistics' end,
      v_duration,jsonb_build_object('rule','3_short_in_last_10_day','threshold_seconds',v_limit)
    ) on conflict(match_id) do nothing;

    foreach v_player in array v_triggered loop
      select * into v_sanction from public.tt_v78_create_sanction(
        v_player,p_match_id,v_competitive_involved,
        jsonb_build_object('duration_seconds',v_duration,'match_type',v_type,'short_matches',3,'window_size',10)
      );
      update public.auto_moderation_cases_v77
      set status='suspended',score=3,distinct_matches=3,distinct_signal_types=1,
          evaluation_mode='enforce',suspension_until=v_sanction.ends_at,
          evidence=v_sanction.evidence,updated_at=now()
      where user_id=v_player and status in('observed','would_suspend','suspended');
      if not found then
        insert into public.auto_moderation_cases_v77(
          user_id,status,score,distinct_matches,distinct_signal_types,
          evaluation_mode,suspension_until,evidence
        ) values(v_player,'suspended',3,3,1,'enforce',v_sanction.ends_at,v_sanction.evidence);
      end if;
    end loop;
    return jsonb_build_object(
      'integrity_hold',true,'match_id',p_match_id,'duration_seconds',v_duration,
      'triggered_users',v_triggered,'message','El resultado quedó en revisión de integridad y todavía no modificó Elo ni estadísticas.'
    );
  end if;

  perform public.confirm_match_result(p_match_id);
  return jsonb_build_object('confirmed',true,'match_id',p_match_id);
end;
$function$;

-- Impide iniciar o aceptar desafíos oficiales durante la restricción.
create or replace function public.tt_v78_challenge_guard()
returns trigger
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_user uuid:=auth.uid();
  v_doc jsonb:=to_jsonb(new);
  v_type text:=lower(coalesce(v_doc->>'match_type','ranked'));
  v_sanction public.integrity_sanctions_v78%rowtype;
begin
  if v_user is null or public.tt_v77_is_protected_user(v_user) then return new; end if;
  select * into v_sanction from public.tt_v78_active_sanction(v_user);
  if v_sanction.id is null then return new; end if;
  if (v_type='casual' and v_sanction.casual_locked)
     or (v_type<>'casual' and v_sanction.competitive_locked) then
    raise exception 'Modalidad bloqueada hasta %. Podés apelar desde el aviso de integridad.',
      to_char(v_sanction.ends_at at time zone 'America/Montevideo','DD/MM/YYYY HH24:MI');
  end if;
  return new;
end;
$function$;

create or replace function public.tt_v78_existing_sanction_result_guard()
returns trigger
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_user uuid:=auth.uid();
  v_doc jsonb:=to_jsonb(new);
  v_old_doc jsonb:=to_jsonb(old);
  v_type text:=lower(coalesce(v_doc->>'match_type','ranked'));
  v_sanction public.integrity_sanctions_v78%rowtype;
begin
  if lower(coalesce(v_doc->>'result_status',''))<>'confirmed'
     or lower(coalesce(v_old_doc->>'result_status',''))='confirmed'
     or v_user is null or public.tt_v77_is_protected_user(v_user) then return new; end if;
  select * into v_sanction from public.tt_v78_active_sanction(v_user);
  if v_sanction.id is null then return new; end if;
  if (v_type='casual' and v_sanction.casual_locked)
     or (v_type<>'casual' and v_sanction.competitive_locked) then
    raise exception 'No podés confirmar esta modalidad hasta %. La sanción es apelable.',
      to_char(v_sanction.ends_at at time zone 'America/Montevideo','DD/MM/YYYY HH24:MI');
  end if;
  return new;
end;
$function$;

drop trigger if exists challenge_integrity_guard_v78 on public.challenges;
create trigger challenge_integrity_guard_v78
before insert or update of status on public.challenges
for each row execute function public.tt_v78_challenge_guard();

drop trigger if exists match_existing_sanction_guard_v78 on public.matches;
create trigger match_existing_sanction_guard_v78
before update of result_status on public.matches
for each row execute function public.tt_v78_existing_sanction_result_guard();

do $optional_doubles$
begin
  if to_regclass('public.doubles_challenges_v62') is not null then
    execute 'drop trigger if exists doubles_challenge_integrity_guard_v78 on public.doubles_challenges_v62';
    execute 'create trigger doubles_challenge_integrity_guard_v78 before insert or update of status on public.doubles_challenges_v62 for each row execute function public.tt_v78_challenge_guard()';
  end if;
  if to_regclass('public.doubles_matches_v62') is not null then
    execute 'drop trigger if exists doubles_match_existing_sanction_guard_v78 on public.doubles_matches_v62';
    execute 'create trigger doubles_match_existing_sanction_guard_v78 before update of result_status on public.doubles_matches_v62 for each row execute function public.tt_v78_existing_sanction_result_guard()';
  end if;
end;
$optional_doubles$;

create or replace function public.get_my_integrity_status_v78()
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_user uuid:=auth.uid();
  v_sanction jsonb;
  v_holds jsonb;
  v_notifications jsonb;
begin
  if v_user is null then raise exception 'Sesión requerida'; end if;
  perform public.tt_v78_expire_sanctions();
  select to_jsonb(s) into v_sanction
  from public.integrity_sanctions_v78 s
  where s.user_id=v_user and s.status='active' and s.ends_at>now()
  order by s.created_at desc limit 1;
  select coalesce(jsonb_agg(to_jsonb(h) order by h.created_at desc),'[]'::jsonb) into v_holds
  from public.integrity_match_holds_v78 h
  where h.status='pending' and v_user=any(h.participants);
  select coalesce(jsonb_agg(to_jsonb(n) order by n.created_at desc),'[]'::jsonb) into v_notifications
  from public.integrity_notifications_v78 n
  where n.user_id=v_user and n.read_at is null;
  update public.integrity_notifications_v78 set read_at=now()
  where user_id=v_user and read_at is null;
  return jsonb_build_object(
    'active',v_sanction is not null,'sanction',v_sanction,
    'pending_holds',v_holds,'notifications',v_notifications
  );
end;
$function$;

create or replace function public.submit_integrity_appeal_v78(p_message text)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare v_user uuid:=auth.uid();v_id bigint;
begin
  if v_user is null then raise exception 'Sesión requerida'; end if;
  if length(trim(coalesce(p_message,'')))<10 then raise exception 'Contanos brevemente qué ocurrió'; end if;
  update public.integrity_sanctions_v78
  set appealed_at=now(),appeal_message=left(trim(p_message),2000),updated_at=now()
  where id=(select s.id from public.integrity_sanctions_v78 s
    where s.user_id=v_user and s.status='active' and s.ends_at>now()
    order by s.created_at desc limit 1)
  returning id into v_id;
  if v_id is null then raise exception 'No hay una sanción activa para apelar'; end if;
  return jsonb_build_object('appealed',true,'sanction_id',v_id);
end;
$function$;

create or replace function public.admin_resolve_integrity_hold_v78(
  p_match_id bigint,p_action text,p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_admin uuid:=auth.uid();
  v_hold public.integrity_match_holds_v78%rowtype;
  v_match public.matches%rowtype;
  v_doc jsonb;
  v_submitter uuid;
  v_confirmer uuid;
  v_old_sub text:=current_setting('request.jwt.claim.sub',true);
  v_old_claims text:=current_setting('request.jwt.claims',true);
begin
  if not public.tt_v58_is_admin(v_admin) then raise exception 'Solo Administrador'; end if;
  if p_action not in('approve','annul') then raise exception 'Acción inválida'; end if;
  select * into v_hold from public.integrity_match_holds_v78
  where match_id=p_match_id and status='pending' for update;
  if not found then raise exception 'La retención no existe o ya fue resuelta'; end if;
  select * into v_match from public.matches where id=p_match_id for update;
  if not found then raise exception 'Partido no encontrado'; end if;

  if p_action='approve' then
    update public.integrity_match_holds_v78
    set status='approved',resolved_at=now(),resolved_by=v_admin,resolution_note=nullif(trim(coalesce(p_note,'')),'')
    where match_id=p_match_id;
    update public.auto_moderation_signals_v77 set active=false where match_id=p_match_id;
    update public.integrity_sanctions_v78
    set status='revoked',reviewed_by=v_admin,reviewed_at=now(),review_note='Partido validado por Admin',updated_at=now()
    where trigger_match_id=p_match_id and status='active';
    v_doc:=to_jsonb(v_match);
    v_submitter:=nullif(v_doc->>'result_submitted_by','')::uuid;
    v_confirmer:=case when v_submitter=v_match.player1_id then v_match.player2_id else v_match.player1_id end;
    perform set_config('request.jwt.claim.sub',v_confirmer::text,true);
    perform set_config('request.jwt.claims',jsonb_build_object('sub',v_confirmer,'role','authenticated')::text,true);
    perform public.confirm_match_result(p_match_id);
    perform set_config('request.jwt.claim.sub',coalesce(v_old_sub,''),true);
    perform set_config('request.jwt.claims',coalesce(v_old_claims,'{}'),true);
    update public.auto_moderation_cases_v77
    set status='dismissed',reviewed_by=v_admin,review_note='Partido validado por Admin',updated_at=now()
    where user_id=any(v_hold.triggered_users) and status in('observed','would_suspend','suspended');
    insert into public.integrity_notifications_v78(user_id,title,message)
    select participant,'Decisión de integridad: partido validado',
      'El partido #'||p_match_id||' fue validado por el administrador y sus consecuencias oficiales fueron aplicadas.'
    from unnest(v_hold.participants) as u(participant);
  else
    update public.matches set result_status='annulled',confirmed_at=null where id=p_match_id;
    update public.integrity_match_holds_v78
    set status='annulled',resolved_at=now(),resolved_by=v_admin,resolution_note=nullif(trim(coalesce(p_note,'')),'')
    where match_id=p_match_id;
    insert into public.integrity_notifications_v78(user_id,title,message)
    select participant,'Decisión de integridad: partido anulado',
      'El partido #'||p_match_id||' fue anulado y no aportará Elo ni estadísticas oficiales.'
    from unnest(v_hold.participants) as u(participant);
  end if;
  return public.admin_get_auto_moderation_v77(50);
end;
$function$;

create or replace function public.admin_get_auto_moderation_v77(p_limit integer default 50)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare v_admin uuid:=auth.uid();v_config jsonb;v_cases jsonb;v_summary jsonb;v_holds jsonb;
begin
  if not public.tt_v58_is_admin(v_admin) then raise exception 'Solo Administrador'; end if;
  perform public.tt_v78_expire_sanctions();
  select to_jsonb(c) into v_config from tt_private_v77.auto_moderation_config_v77 c where singleton=true;
  select jsonb_build_object(
    'open_cases',count(*) filter(where status in('observed','would_suspend','suspended')),
    'threshold_cases',count(*) filter(where status in('would_suspend','suspended')),
    'automatic_suspensions',(select count(*) from public.integrity_sanctions_v78 where status='active' and ends_at>now()),
    'pending_holds',(select count(*) from public.integrity_match_holds_v78 where status='pending')
  ) into v_summary from public.auto_moderation_cases_v77;
  select coalesce(jsonb_agg(to_jsonb(x) order by x.updated_at desc),'[]'::jsonb) into v_cases
  from(
    select c.id,c.user_id,c.status,c.score,c.distinct_matches,c.distinct_signal_types,
      c.evaluation_mode,c.suspension_until,c.evidence,c.created_at,c.updated_at,c.review_note,
      p.username,p.first_name,p.last_name,p.profile_photo_url,
      to_jsonb(s) as sanction
    from public.auto_moderation_cases_v77 c
    left join public.profiles p on p.id=c.user_id
    left join lateral(
      select sx.* from public.integrity_sanctions_v78 sx
      where sx.user_id=c.user_id order by sx.created_at desc limit 1
    ) s on true
    where c.status in('observed','would_suspend','suspended')
    order by c.updated_at desc limit greatest(1,least(200,coalesce(p_limit,50)))
  ) x;
  select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc),'[]'::jsonb) into v_holds
  from(
    select h.*,p1.username as player1_username,p2.username as player2_username
    from public.integrity_match_holds_v78 h
    left join public.matches m on m.id=h.match_id
    left join public.profiles p1 on p1.id=m.player1_id
    left join public.profiles p2 on p2.id=m.player2_id
    where h.status='pending'
    order by h.created_at desc limit 100
  ) x;
  return jsonb_build_object('config',v_config,'summary',v_summary,'cases',v_cases,'holds',v_holds);
end;
$function$;

create or replace function public.admin_reprocess_auto_moderation_v77(
  p_days integer default 7,p_limit integer default 500
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare v_admin uuid:=auth.uid();v_days integer:=greatest(1,least(14,coalesce(p_days,7)));v_limit integer:=greatest(1,least(1000,coalesce(p_limit,500)));v_row record;v_count integer:=0;
begin
  if not public.tt_v58_is_admin(v_admin) then raise exception 'Solo Administrador'; end if;
  if (select mode from tt_private_v77.auto_moderation_config_v77 where singleton=true)='paused' then
    raise exception 'El motor está pausado. Elegí Simulación antes de reanalizar';
  end if;
  update public.auto_moderation_signals_v77 set active=false
  where created_at>=now()-make_interval(days=>v_days);
  update public.auto_moderation_cases_v77 set status='cleared',updated_at=now()
  where status in('observed','would_suspend');
  for v_row in
    select m.id,public.tt_v78_match_occurred_at(to_jsonb(m)) occurred_at
    from public.matches m
    where lower(coalesce(to_jsonb(m)->>'result_status',''))='confirmed'
      and lower(coalesce(to_jsonb(m)->>'match_type','ranked')) in('ranked','competitive','casual')
      and public.tt_v78_match_occurred_at(to_jsonb(m))>=now()-make_interval(days=>v_days)
    order by occurred_at asc limit v_limit
  loop
    perform public.tt_v77_evaluate_match(v_row.id,false);v_count:=v_count+1;
  end loop;
  return public.admin_get_auto_moderation_v77(50)||jsonb_build_object('reprocessed_matches',v_count);
end;
$function$;

-- La confirmación pública pasa únicamente por la puerta de integridad.
revoke execute on function public.confirm_match_result(bigint) from public,anon,authenticated;
revoke all on function public.confirm_match_result_integrity_v78(bigint) from public,anon;
revoke all on function public.get_my_integrity_status_v78() from public,anon;
revoke all on function public.submit_integrity_appeal_v78(text) from public,anon;
grant execute on function public.confirm_match_result_integrity_v78(bigint) to authenticated;
grant execute on function public.get_my_integrity_status_v78() to authenticated;
grant execute on function public.submit_integrity_appeal_v78(text) to authenticated;
revoke all on function public.admin_resolve_integrity_hold_v78(bigint,text,text) from public,anon;
grant execute on function public.admin_resolve_integrity_hold_v78(bigint,text,text) to authenticated;

revoke all on function public.tt_v78_match_occurred_at(jsonb) from public,anon,authenticated;
revoke all on function public.tt_v78_match_duration_seconds(jsonb) from public,anon,authenticated;
revoke all on function public.tt_v78_expire_sanctions() from public,anon,authenticated;
revoke all on function public.tt_v78_active_sanction(uuid) from public,anon,authenticated;
revoke all on function public.tt_v78_create_sanction(uuid,bigint,boolean,jsonb) from public,anon,authenticated;
revoke all on function public.tt_v78_best_short_window(uuid) from public,anon,authenticated;
revoke all on function public.tt_v78_challenge_guard() from public,anon,authenticated;
revoke all on function public.tt_v78_existing_sanction_result_guard() from public,anon,authenticated;

notify pgrst,'reload schema';
commit;

select jsonb_build_object(
  'resultado','P7.4R.4.1 instalado',
  'modo','observe',
  'regla','3 partidos menores a 60 segundos entre los últimos 10 del día',
  'incluye','ranked y casuales individuales',
  'sanciones_reales',false,
  'siguiente_paso','Admin > Partidos sospechosos > Reanalizar 7 días'
) as resultado;

