-- TT Rivals 1.0.1 — P7.4R.2 Control de acceso y baneos
-- Tipos: temporal de cuenta, permanente de correo, dispositivo e IP/red.
-- Las IP se guardan como HMAC; la interfaz nunca recibe la IP real.

begin;

create extension if not exists pgcrypto with schema extensions;
create schema if not exists tt_private_v75;

create table if not exists tt_private_v75.tt_access_secrets_v75(
  name text primary key,
  secret bytea not null,
  created_at timestamptz not null default now()
);

insert into tt_private_v75.tt_access_secrets_v75(name,secret)
values('ip_hmac',extensions.gen_random_bytes(32))
on conflict(name) do nothing;

revoke all on schema tt_private_v75 from public,anon,authenticated;
revoke all on all tables in schema tt_private_v75 from public,anon,authenticated;

create table if not exists public.account_access_bans_v75(
  id bigint generated by default as identity primary key,
  user_id uuid,
  email_key text not null,
  ban_type text not null check(ban_type in('temporary','email_permanent')),
  blocked_until timestamptz,
  active boolean not null default true,
  created_by uuid not null,
  created_at timestamptz not null default now(),
  revoked_by uuid,
  revoked_at timestamptz,
  constraint account_access_bans_v75_window check(
    (ban_type='temporary' and blocked_until is not null)
    or (ban_type='email_permanent' and blocked_until is null)
  )
);

create unique index if not exists account_access_bans_v75_active_email_idx
on public.account_access_bans_v75(email_key)
where active;

create table if not exists public.device_access_bans_v75(
  installation_id uuid primary key,
  source_user_id uuid,
  active boolean not null default true,
  created_by uuid not null,
  created_at timestamptz not null default now(),
  revoked_by uuid,
  revoked_at timestamptz
);

create table if not exists public.ip_access_bans_v75(
  ip_hash text primary key,
  source_user_id uuid,
  active boolean not null default true,
  created_by uuid not null,
  created_at timestamptz not null default now(),
  revoked_by uuid,
  revoked_at timestamptz
);

create table if not exists public.access_observations_v75(
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  email_key text,
  installation_id uuid,
  ip_hash text,
  source text not null check(source in('signup','session')),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create unique index if not exists access_observations_v75_identity_idx
on public.access_observations_v75(user_id,coalesce(installation_id,'00000000-0000-0000-0000-000000000000'::uuid),coalesce(ip_hash,''));

create table if not exists public.access_ban_audit_v75(
  id bigint generated by default as identity primary key,
  target_user_id uuid not null,
  admin_id uuid not null,
  action text not null,
  ban_type text,
  blocked_until timestamptz,
  affected_items integer not null default 0,
  note text,
  created_at timestamptz not null default now()
);

alter table public.account_access_bans_v75 enable row level security;
alter table public.device_access_bans_v75 enable row level security;
alter table public.ip_access_bans_v75 enable row level security;
alter table public.access_observations_v75 enable row level security;
alter table public.access_ban_audit_v75 enable row level security;

revoke all on public.account_access_bans_v75 from public,anon,authenticated;
revoke all on public.device_access_bans_v75 from public,anon,authenticated;
revoke all on public.ip_access_bans_v75 from public,anon,authenticated;
revoke all on public.access_observations_v75 from public,anon,authenticated;
revoke all on public.access_ban_audit_v75 from public,anon,authenticated;

create or replace function public.tt_v75_email_key(p_email text)
returns text
language plpgsql
immutable
set search_path=''
as $function$
declare
  v_email text:=lower(trim(coalesce(p_email,'')));
  v_local text;
  v_domain text;
begin
  if position('@' in v_email)=0 then return v_email; end if;
  v_local:=split_part(v_email,'@',1);
  v_domain:=split_part(v_email,'@',2);
  if v_domain in('gmail.com','googlemail.com') then
    v_local:=split_part(v_local,'+',1);
    v_local:=replace(v_local,'.','');
    v_domain:='gmail.com';
  end if;
  return v_local||'@'||v_domain;
end;
$function$;

create or replace function public.tt_v75_ip_hash(p_ip text)
returns text
language sql
stable
security definer
set search_path=''
as $function$
  select case when nullif(trim(p_ip),'') is null then null else
    encode(extensions.hmac(convert_to(trim(p_ip),'utf8'),s.secret,'sha256'),'hex')
  end
  from tt_private_v75.tt_access_secrets_v75 s
  where s.name='ip_hmac';
$function$;

create or replace function public.tt_v75_request_ip()
returns text
language plpgsql
stable
set search_path=''
as $function$
declare v_headers jsonb;
begin
  begin
    v_headers:=nullif(current_setting('request.headers',true),'')::jsonb;
  exception when others then
    v_headers:='{}'::jsonb;
  end;
  return nullif(trim(split_part(coalesce(v_headers->>'x-forwarded-for',''),',',1)),'');
end;
$function$;

create or replace function public.tt_v75_access_decision(
  p_email text default null,
  p_installation_id uuid default null,
  p_user_id uuid default null,
  p_ip text default null,
  p_record boolean default false,
  p_source text default 'session'
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_user_id uuid:=coalesce(p_user_id,auth.uid());
  v_email text:=p_email;
  v_email_key text;
  v_ip text:=coalesce(p_ip,public.tt_v75_request_ip());
  v_ip_hash text:=public.tt_v75_ip_hash(v_ip);
  v_until timestamptz;
begin
  if v_email is null and v_user_id is not null then
    select u.email into v_email from auth.users u where u.id=v_user_id;
  end if;
  v_email_key:=public.tt_v75_email_key(v_email);

  if exists(
    select 1 from public.account_access_bans_v75 b
    where b.active and b.email_key=v_email_key and b.ban_type='email_permanent'
  ) then
    return jsonb_build_object('allowed',false,'kind','email_permanent','message','Tu cuenta ha sido baneada permanentemente');
  end if;

  select max(b.blocked_until) into v_until
  from public.account_access_bans_v75 b
  where b.active and b.ban_type='temporary'
    and b.blocked_until>now()
    and (b.email_key=v_email_key or (v_user_id is not null and b.user_id=v_user_id));

  if v_until is not null then
    return jsonb_build_object(
      'allowed',false,'kind','temporary','until',v_until,
      'message','Has sido baneado temporalmente. Tu cuenta será habilitada a partir del día '||
        to_char(v_until at time zone 'America/Montevideo','DD/MM/YYYY "a las" HH24:MI')
    );
  end if;

  if p_installation_id is not null and exists(
    select 1 from public.device_access_bans_v75 b
    where b.active and b.installation_id=p_installation_id
  ) then
    return jsonb_build_object('allowed',false,'kind','device_permanent','message','Ya no puedes utilizar la aplicación en este dispositivo');
  end if;

  if v_ip_hash is not null and exists(
    select 1 from public.ip_access_bans_v75 b
    where b.active and b.ip_hash=v_ip_hash
  ) then
    return jsonb_build_object('allowed',false,'kind','ip_permanent','message','Ya no puedes utilizar la aplicación desde esta red');
  end if;

  if p_record and v_user_id is not null then
    insert into public.access_observations_v75(user_id,email_key,installation_id,ip_hash,source)
    values(v_user_id,v_email_key,p_installation_id,v_ip_hash,
      case when p_source='signup' then 'signup' else 'session' end)
    on conflict(user_id,coalesce(installation_id,'00000000-0000-0000-0000-000000000000'::uuid),coalesce(ip_hash,''))
    do update set email_key=excluded.email_key,last_seen_at=now(),source=excluded.source;
  end if;

  return jsonb_build_object('allowed',true);
end;
$function$;

create or replace function public.check_access_gate_v75(
  p_email text default null,
  p_installation_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
begin
  return public.tt_v75_access_decision(
    p_email,p_installation_id,auth.uid(),public.tt_v75_request_ip(),auth.uid() is not null,'session'
  );
end;
$function$;

create or replace function public.hook_before_user_created_v75(event jsonb)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_user_id uuid:=(event->'user'->>'id')::uuid;
  v_email text:=event->'user'->>'email';
  v_installation uuid;
  v_ip text:=event->'metadata'->>'ip_address';
  v_decision jsonb;
begin
  begin
    v_installation:=nullif(event->'user'->'user_metadata'->>'installation_id','')::uuid;
  exception when others then
    v_installation:=null;
  end;

  v_decision:=public.tt_v75_access_decision(v_email,v_installation,v_user_id,v_ip,false,'signup');
  if not coalesce((v_decision->>'allowed')::boolean,false) then
    return jsonb_build_object('error',jsonb_build_object(
      'http_code',403,
      'message',v_decision->>'message'
    ));
  end if;

  perform public.tt_v75_access_decision(v_email,v_installation,v_user_id,v_ip,true,'signup');
  return '{}'::jsonb;
end;
$function$;

create or replace function public.admin_get_user_ban_v75(p_user_id uuid)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_email text;
  v_key text;
  v_account jsonb;
  v_devices integer;
  v_ips integer;
begin
  if not public.tt_v58_is_admin(auth.uid()) then raise exception 'Solo Administrador'; end if;
  select u.email into v_email from auth.users u where u.id=p_user_id;
  if v_email is null then raise exception 'Usuario no encontrado'; end if;
  v_key:=public.tt_v75_email_key(v_email);

  select jsonb_build_object('type',b.ban_type,'until',b.blocked_until,'created_at',b.created_at)
    into v_account
  from public.account_access_bans_v75 b
  where b.active and b.email_key=v_key
  order by b.created_at desc limit 1;

  select count(*) into v_devices from public.device_access_bans_v75 b
    where b.active and b.source_user_id=p_user_id;
  select count(*) into v_ips from public.ip_access_bans_v75 b
    where b.active and b.source_user_id=p_user_id;

  return jsonb_build_object(
    'user_id',p_user_id,'email',v_email,'account_ban',v_account,
    'device_bans',v_devices,'ip_bans',v_ips
  );
end;
$function$;

create or replace function public.admin_apply_user_ban_v75(
  p_user_id uuid,
  p_ban_type text,
  p_days integer default null,
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_admin uuid:=auth.uid();
  v_email text;
  v_key text;
  v_until timestamptz;
  v_count integer:=0;
begin
  if not public.tt_v58_is_admin(v_admin) then raise exception 'Solo Administrador'; end if;
  if p_user_id=v_admin then raise exception 'No podés banear tu propia cuenta administrativa'; end if;
  if p_ban_type not in('temporary','email_permanent','device_permanent','ip_permanent','unban') then
    raise exception 'Tipo de baneo inválido';
  end if;

  select u.email into v_email from auth.users u where u.id=p_user_id for update;
  if v_email is null then raise exception 'Usuario no encontrado'; end if;
  v_key:=public.tt_v75_email_key(v_email);

  if p_ban_type='unban' then
    update public.account_access_bans_v75 set active=false,revoked_by=v_admin,revoked_at=now()
      where active and (user_id=p_user_id or email_key=v_key);
    update public.device_access_bans_v75 set active=false,revoked_by=v_admin,revoked_at=now()
      where active and source_user_id=p_user_id;
    update public.ip_access_bans_v75 set active=false,revoked_by=v_admin,revoked_at=now()
      where active and source_user_id=p_user_id;
    update auth.users set banned_until=null where id=p_user_id;
  elsif p_ban_type='temporary' then
    if coalesce(p_days,0)<1 or p_days>365 then raise exception 'Elegí entre 1 y 365 días'; end if;
    v_until:=now()+make_interval(days=>p_days);
    update public.account_access_bans_v75 set active=false,revoked_by=v_admin,revoked_at=now()
      where active and email_key=v_key;
    insert into public.account_access_bans_v75(user_id,email_key,ban_type,blocked_until,created_by)
      values(p_user_id,v_key,'temporary',v_until,v_admin);
    update auth.users set banned_until=v_until where id=p_user_id;
    delete from auth.sessions where user_id=p_user_id;
    v_count:=1;
  elsif p_ban_type='email_permanent' then
    update public.account_access_bans_v75 set active=false,revoked_by=v_admin,revoked_at=now()
      where active and email_key=v_key;
    insert into public.account_access_bans_v75(user_id,email_key,ban_type,blocked_until,created_by)
      values(p_user_id,v_key,'email_permanent',null,v_admin);
    update auth.users set banned_until=now()+interval '100 years' where id=p_user_id;
    delete from auth.sessions where user_id=p_user_id;
    v_count:=1;
  elsif p_ban_type='device_permanent' then
    insert into public.device_access_bans_v75(installation_id,source_user_id,created_by)
    select distinct a.installation_id,p_user_id,v_admin
    from public.installation_accounts_v58 a where a.user_id=p_user_id
    on conflict(installation_id) do update set active=true,source_user_id=excluded.source_user_id,
      created_by=excluded.created_by,created_at=now(),revoked_by=null,revoked_at=null;
    get diagnostics v_count=row_count;
    if v_count=0 then raise exception 'Todavía no hay un dispositivo registrado para este usuario'; end if;
    delete from auth.sessions where user_id=p_user_id;
  elsif p_ban_type='ip_permanent' then
    insert into public.ip_access_bans_v75(ip_hash,source_user_id,created_by)
    select distinct o.ip_hash,p_user_id,v_admin
    from public.access_observations_v75 o where o.user_id=p_user_id and o.ip_hash is not null
    on conflict(ip_hash) do update set active=true,source_user_id=excluded.source_user_id,
      created_by=excluded.created_by,created_at=now(),revoked_by=null,revoked_at=null;
    get diagnostics v_count=row_count;
    if v_count=0 then raise exception 'Todavía no hay una IP registrada para este usuario'; end if;
    delete from auth.sessions where user_id=p_user_id;
  end if;

  insert into public.access_ban_audit_v75(target_user_id,admin_id,action,ban_type,blocked_until,affected_items,note)
  values(p_user_id,v_admin,case when p_ban_type='unban' then 'unban' else 'ban' end,
    nullif(p_ban_type,'unban'),v_until,v_count,nullif(trim(coalesce(p_note,'')),''));

  return public.admin_get_user_ban_v75(p_user_id);
end;
$function$;

revoke all on function public.tt_v75_email_key(text) from public,anon,authenticated;
revoke all on function public.tt_v75_ip_hash(text) from public,anon,authenticated;
revoke all on function public.tt_v75_request_ip() from public,anon,authenticated;
revoke all on function public.tt_v75_access_decision(text,uuid,uuid,text,boolean,text) from public,anon,authenticated;
revoke all on function public.hook_before_user_created_v75(jsonb) from public,anon,authenticated;
grant execute on function public.hook_before_user_created_v75(jsonb) to supabase_auth_admin;

revoke all on function public.check_access_gate_v75(text,uuid) from public;
grant execute on function public.check_access_gate_v75(text,uuid) to anon,authenticated;

revoke all on function public.admin_get_user_ban_v75(uuid) from public,anon;
revoke all on function public.admin_apply_user_ban_v75(uuid,text,integer,text) from public,anon;
grant execute on function public.admin_get_user_ban_v75(uuid) to authenticated;
grant execute on function public.admin_apply_user_ban_v75(uuid,text,integer,text) to authenticated;

commit;

select 'P7.4R.2: control de acceso instalado. Activá hook_before_user_created_v75 como Before User Created Hook.' as resultado;
