-- TT Rivals 1.0.1 — P7.4R.4 Moderación automática prudente
-- Se instala en modo OBSERVE: detecta y audita, pero no suspende usuarios.
-- Requiere P7.4R.2, P7.4R.3 y el hotfix P7.4R.3.1.

begin;

do $preflight$
begin
  if to_regclass('public.account_access_bans_v75') is null then
    raise exception 'Falta P7.4R.2: account_access_bans_v75 no existe';
  end if;
  if to_regclass('public.installation_accounts_v58') is null then
    raise exception 'Falta el sistema V58 de instalaciones';
  end if;
  if to_regclass('public.installation_pair_exceptions_v58') is null then
    raise exception 'Falta el sistema V58 de excepciones entre cuentas vinculadas';
  end if;
  if to_regclass('public.matches') is null then
    raise exception 'La tabla public.matches no existe';
  end if;
end;
$preflight$;

create schema if not exists tt_private_v77;
revoke all on schema tt_private_v77 from public,anon,authenticated;

create table if not exists tt_private_v77.auto_moderation_config_v77(
  singleton boolean primary key default true check(singleton),
  mode text not null default 'observe' check(mode in('observe','enforce','paused')),
  score_threshold integer not null default 100 check(score_threshold between 50 and 500),
  lookback_days integer not null default 7 check(lookback_days between 1 and 30),
  min_matches integer not null default 3 check(min_matches between 2 and 20),
  min_signal_types integer not null default 2 check(min_signal_types between 2 and 4),
  base_suspension_hours integer not null default 24 check(base_suspension_hours between 1 and 168),
  updated_by uuid,
  updated_at timestamptz not null default now()
);

insert into tt_private_v77.auto_moderation_config_v77(singleton,mode)
values(true,'observe')
on conflict(singleton) do nothing;

revoke all on all tables in schema tt_private_v77 from public,anon,authenticated;

create table if not exists public.auto_moderation_signals_v77(
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  opponent_id uuid,
  match_id bigint not null,
  signal_type text not null check(signal_type in(
    'duration_extreme','repeated_pair','linked_installation','activity_burst'
  )),
  points integer not null check(points between 1 and 100),
  evidence jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index if not exists auto_moderation_signals_v77_unique_idx
on public.auto_moderation_signals_v77(user_id,match_id,signal_type);

create index if not exists auto_moderation_signals_v77_user_date_idx
on public.auto_moderation_signals_v77(user_id,created_at desc)
where active;

create table if not exists public.auto_moderation_cases_v77(
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  status text not null check(status in(
    'observed','would_suspend','suspended','dismissed','cleared'
  )),
  score integer not null default 0,
  distinct_matches integer not null default 0,
  distinct_signal_types integer not null default 0,
  evaluation_mode text not null check(evaluation_mode in('observe','enforce','paused')),
  suspension_until timestamptz,
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  reviewed_by uuid,
  review_note text
);

create unique index if not exists auto_moderation_cases_v77_open_user_idx
on public.auto_moderation_cases_v77(user_id)
where status in('observed','would_suspend','suspended');

create index if not exists auto_moderation_cases_v77_updated_idx
on public.auto_moderation_cases_v77(updated_at desc);

create table if not exists public.auto_moderation_actions_v77(
  id bigint generated by default as identity primary key,
  case_id bigint,
  user_id uuid,
  action text not null,
  mode text,
  details jsonb not null default '{}'::jsonb,
  actor_id uuid,
  created_at timestamptz not null default now()
);

create index if not exists auto_moderation_actions_v77_user_date_idx
on public.auto_moderation_actions_v77(user_id,created_at desc);

-- Mantiene ligera la evaluación que ocurre al confirmar un partido.
create index if not exists matches_v77_player1_confirmed_idx
on public.matches(player1_id,confirmed_at desc)
where result_status='confirmed';

create index if not exists matches_v77_player2_confirmed_idx
on public.matches(player2_id,confirmed_at desc)
where result_status='confirmed';

create index if not exists installation_accounts_v77_user_installation_idx
on public.installation_accounts_v58(user_id,installation_id);

alter table public.auto_moderation_signals_v77 enable row level security;
alter table public.auto_moderation_cases_v77 enable row level security;
alter table public.auto_moderation_actions_v77 enable row level security;

revoke all on public.auto_moderation_signals_v77 from public,anon,authenticated;
revoke all on public.auto_moderation_cases_v77 from public,anon,authenticated;
revoke all on public.auto_moderation_actions_v77 from public,anon,authenticated;

create or replace function public.tt_v77_json_number(p_doc jsonb,p_key text)
returns numeric
language plpgsql
immutable
set search_path=''
as $function$
begin
  return nullif(p_doc->>p_key,'')::numeric;
exception when others then
  return null;
end;
$function$;

create or replace function public.tt_v77_json_boolean(p_doc jsonb,p_key text)
returns boolean
language sql
immutable
set search_path=''
as $function$
  select lower(coalesce(p_doc->>p_key,'')) in('true','t','1','yes','on');
$function$;

create or replace function public.tt_v77_is_protected_user(p_user_id uuid)
returns boolean
language plpgsql
stable
security definer
set search_path=''
as $function$
declare v_profile jsonb;
begin
  if p_user_id is null then return true; end if;
  if public.tt_v58_is_admin(p_user_id) then return true; end if;
  select to_jsonb(p) into v_profile from public.profiles p where p.id=p_user_id;
  return public.tt_v77_json_boolean(coalesce(v_profile,'{}'::jsonb),'is_test_admin');
end;
$function$;

create or replace function public.tt_v77_pair_has_exception(p_user_a uuid,p_user_b uuid)
returns boolean
language sql
stable
security definer
set search_path=''
as $function$
  select exists(
    select 1
    from public.installation_pair_exceptions_v58 e
    where (e.user_a=p_user_a and e.user_b=p_user_b)
       or (e.user_a=p_user_b and e.user_b=p_user_a)
  );
$function$;

create or replace function public.tt_v77_record_signal(
  p_user_id uuid,
  p_opponent_id uuid,
  p_match_id bigint,
  p_signal_type text,
  p_points integer,
  p_evidence jsonb,
  p_occurred_at timestamptz
)
returns void
language plpgsql
security definer
set search_path=''
as $function$
begin
  if public.tt_v77_is_protected_user(p_user_id) then return; end if;
  if exists(
    select 1 from public.auto_moderation_cases_v77 c
    where c.user_id=p_user_id and c.status='dismissed'
      and c.updated_at>=coalesce(p_occurred_at,now())
  ) then
    -- Un reanálisis histórico no puede reabrir evidencia ya descartada por el Admin.
    return;
  end if;
  if p_signal_type not in('duration_extreme','repeated_pair','linked_installation','activity_burst') then
    raise exception 'Señal de moderación inválida';
  end if;
  insert into public.auto_moderation_signals_v77(
    user_id,opponent_id,match_id,signal_type,points,evidence,created_at
  ) values(
    p_user_id,p_opponent_id,p_match_id,p_signal_type,
    greatest(1,least(100,p_points)),coalesce(p_evidence,'{}'::jsonb),coalesce(p_occurred_at,now())
  )
  on conflict(user_id,match_id,signal_type)
  do update set
    opponent_id=excluded.opponent_id,
    points=excluded.points,
    evidence=excluded.evidence,
    active=true,
    created_at=excluded.created_at;
end;
$function$;

create or replace function public.tt_v77_evaluate_user(
  p_user_id uuid,
  p_allow_enforcement boolean default true
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_config tt_private_v77.auto_moderation_config_v77%rowtype;
  v_case public.auto_moderation_cases_v77%rowtype;
  v_previous_status text;
  v_score integer:=0;
  v_matches integer:=0;
  v_types integer:=0;
  v_status text:='observed';
  v_evidence jsonb:='[]'::jsonb;
  v_email text;
  v_email_key text;
  v_until timestamptz;
  v_previous_suspensions integer:=0;
  v_hours integer:=24;
  v_system uuid:='00000000-0000-0000-0000-000000000077'::uuid;
  v_new_case boolean:=false;
begin
  if public.tt_v77_is_protected_user(p_user_id) then
    return jsonb_build_object('user_id',p_user_id,'protected',true,'status','ignored');
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text,77));
  select * into v_config
  from tt_private_v77.auto_moderation_config_v77
  where singleton=true;

  select
    coalesce(sum(s.points),0)::integer,
    count(distinct s.match_id)::integer,
    count(distinct s.signal_type)::integer,
    coalesce(jsonb_agg(
      jsonb_build_object(
        'signal_type',s.signal_type,'points',s.points,'match_id',s.match_id,
        'opponent_id',s.opponent_id,'occurred_at',s.created_at,'evidence',s.evidence
      ) order by s.created_at desc
    ),'[]'::jsonb)
  into v_score,v_matches,v_types,v_evidence
  from public.auto_moderation_signals_v77 s
  where s.user_id=p_user_id
    and s.active
    and s.created_at>=now()-make_interval(days=>v_config.lookback_days);

  select * into v_case
  from public.auto_moderation_cases_v77 c
  where c.user_id=p_user_id
    and c.status in('observed','would_suspend','suspended')
  order by c.updated_at desc
  limit 1
  for update;
  v_previous_status:=v_case.status;

  if v_score>=v_config.score_threshold
     and v_matches>=v_config.min_matches
     and v_types>=v_config.min_signal_types then
    if v_config.mode='enforce' and p_allow_enforcement then
      v_status:='suspended';
    else
      v_status:='would_suspend';
    end if;
  elsif v_score=0 then
    v_status:='cleared';
  else
    v_status:='observed';
  end if;

  -- Una temporal ya vencida no debe impedir futuras decisiones.
  update public.account_access_bans_v75
  set active=false,revoked_by=v_system,revoked_at=now()
  where active and ban_type='temporary' and blocked_until<=now()
    and user_id=p_user_id;

  -- Reprocesar en simulación nunca debe ocultar una suspensión que todavía está vigente.
  if v_case.status='suspended' then
    select b.blocked_until into v_until
    from public.account_access_bans_v75 b
    where b.active and b.ban_type='temporary' and b.user_id=p_user_id
      and b.blocked_until>now()
    order by b.created_at desc limit 1;
    if found then v_status:='suspended'; end if;
  end if;

  if v_status='suspended' then
    select u.email into v_email from auth.users u where u.id=p_user_id for update;
    if v_email is null then
      v_status:='would_suspend';
    else
      v_email_key:=public.tt_v75_email_key(v_email);
      select b.blocked_until into v_until
      from public.account_access_bans_v75 b
      where b.active and (b.user_id=p_user_id or b.email_key=v_email_key)
      order by b.created_at desc limit 1;

      if not found then
        select count(*)::integer into v_previous_suspensions
        from public.auto_moderation_actions_v77 a
        where a.user_id=p_user_id
          and a.action='automatic_suspension'
          and a.created_at>=now()-interval '90 days';

        v_hours:=case
          when v_previous_suspensions=0 then v_config.base_suspension_hours
          when v_previous_suspensions=1 then greatest(72,v_config.base_suspension_hours)
          else greatest(168,v_config.base_suspension_hours)
        end;
        v_until:=now()+make_interval(hours=>v_hours);

        insert into public.account_access_bans_v75(
          user_id,email_key,ban_type,blocked_until,created_by
        ) values(p_user_id,v_email_key,'temporary',v_until,v_system);

        update auth.users set banned_until=v_until where id=p_user_id;
        delete from auth.sessions where user_id=p_user_id;

        insert into public.access_ban_audit_v75(
          target_user_id,admin_id,action,ban_type,blocked_until,affected_items,note
        ) values(
          p_user_id,v_system,'ban','temporary',v_until,1,
          'Suspensión preventiva automática P7.4R.4. Puntaje '||v_score||
          ', '||v_matches||' partidos y '||v_types||' tipos de señal. Revisable y apelable.'
        );
      end if;
    end if;
  end if;

  if v_status='cleared' then
    if v_case.id is not null then
      update public.auto_moderation_cases_v77
      set status='cleared',score=0,distinct_matches=0,distinct_signal_types=0,
          evaluation_mode=v_config.mode,evidence='[]'::jsonb,updated_at=now()
      where id=v_case.id;
    end if;
    return jsonb_build_object('user_id',p_user_id,'status','cleared','score',0);
  end if;

  if v_case.id is null then
    insert into public.auto_moderation_cases_v77(
      user_id,status,score,distinct_matches,distinct_signal_types,
      evaluation_mode,suspension_until,evidence
    ) values(
      p_user_id,v_status,v_score,v_matches,v_types,v_config.mode,v_until,v_evidence
    ) returning * into v_case;
    v_new_case:=true;
  else
    update public.auto_moderation_cases_v77
    set status=v_status,score=v_score,distinct_matches=v_matches,
        distinct_signal_types=v_types,evaluation_mode=v_config.mode,
        suspension_until=case when v_status='suspended' then v_until else null end,
        evidence=v_evidence,updated_at=now()
    where id=v_case.id
    returning * into v_case;
  end if;

  if v_new_case or v_previous_status is distinct from v_status then
    insert into public.auto_moderation_actions_v77(
      case_id,user_id,action,mode,details,actor_id
    ) values(
      v_case.id,p_user_id,
      case
        when v_status='suspended' then 'automatic_suspension'
        when v_status='would_suspend' then 'simulation_threshold_reached'
        else 'case_observed'
      end,
      v_config.mode,
      jsonb_build_object('score',v_score,'matches',v_matches,'signal_types',v_types,'until',v_until),
      v_system
    );
  end if;

  return jsonb_build_object(
    'case_id',v_case.id,'user_id',p_user_id,'status',v_status,'score',v_score,
    'matches',v_matches,'signal_types',v_types,'suspension_until',v_until
  );
end;
$function$;

create or replace function public.tt_v77_evaluate_match(
  p_match_id bigint,
  p_allow_enforcement boolean default true
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_match public.matches%rowtype;
  v_doc jsonb;
  v_type text;
  v_occurred timestamptz;
  v_risk numeric:=0;
  v_gameplay integer;
  v_anomaly boolean:=false;
  v_mode text:='observe';
  v_player uuid;
  v_opponent uuid;
  v_repeats integer:=0;
  v_burst integer:=0;
  v_shared boolean:=false;
  v_results jsonb:='[]'::jsonb;
begin
  select * into v_match from public.matches m where m.id=p_match_id;
  if not found then return jsonb_build_object('ignored',true,'reason','match_not_found'); end if;

  v_doc:=to_jsonb(v_match);
  if lower(coalesce(v_doc->>'result_status',''))<>'confirmed' then
    return jsonb_build_object('ignored',true,'reason','not_confirmed');
  end if;
  v_type:=lower(coalesce(v_doc->>'match_type',''));
  if v_type not in('ranked','competitive') then
    return jsonb_build_object('ignored',true,'reason','not_ranked');
  end if;
  select c.mode into v_mode
  from tt_private_v77.auto_moderation_config_v77 c
  where c.singleton=true;
  if v_mode='paused' then
    return jsonb_build_object('ignored',true,'reason','paused');
  end if;

  v_occurred:=coalesce(
    nullif(v_doc->>'confirmed_at','')::timestamptz,
    nullif(v_doc->>'created_at','')::timestamptz,
    now()
  );
  v_risk:=coalesce(public.tt_v77_json_number(v_doc,'duration_risk_score_v59'),0);
  v_gameplay:=public.tt_v77_json_number(v_doc,'gameplay_seconds')::integer;
  v_anomaly:=public.tt_v77_json_boolean(v_doc,'duration_anomaly_v59');

  foreach v_player in array array[v_match.player1_id,v_match.player2_id]
  loop
    if v_player is null or public.tt_v77_is_protected_user(v_player) then continue; end if;
    v_opponent:=case when v_player=v_match.player1_id then v_match.player2_id else v_match.player1_id end;

    if v_anomaly or v_risk>=75 or (v_gameplay is not null and v_gameplay<=10) then
      perform public.tt_v77_record_signal(
        v_player,v_opponent,p_match_id,'duration_extreme',
        case when v_risk>=90 or coalesce(v_gameplay,999)<=10 then 40 else 30 end,
        jsonb_build_object('duration_risk',v_risk,'gameplay_seconds',v_gameplay,'anomaly',v_anomaly),
        v_occurred
      );
    end if;

    select count(*)::integer into v_repeats
    from public.matches m
    where lower(coalesce(to_jsonb(m)->>'result_status',''))='confirmed'
      and lower(coalesce(to_jsonb(m)->>'match_type','')) in('ranked','competitive')
      and (
        (m.player1_id=v_player and m.player2_id=v_opponent)
        or (m.player1_id=v_opponent and m.player2_id=v_player)
      )
      and coalesce(
        nullif(to_jsonb(m)->>'confirmed_at','')::timestamptz,
        nullif(to_jsonb(m)->>'created_at','')::timestamptz
      ) between v_occurred-interval '24 hours' and v_occurred+interval '1 second';

    if v_repeats>=4 then
      perform public.tt_v77_record_signal(
        v_player,v_opponent,p_match_id,'repeated_pair',
        case when v_repeats>=6 then 35 else 25 end,
        jsonb_build_object('pair_matches_24h',v_repeats),v_occurred
      );
    end if;

    select exists(
      select 1
      from public.installation_accounts_v58 a
      join public.installation_accounts_v58 b
        on b.installation_id=a.installation_id
       and b.user_id=v_opponent
      where a.user_id=v_player
        and not public.tt_v77_pair_has_exception(v_player,v_opponent)
    ) into v_shared;

    if v_shared then
      perform public.tt_v77_record_signal(
        v_player,v_opponent,p_match_id,'linked_installation',45,
        jsonb_build_object('shared_installation',true,'authorized_exception',false),v_occurred
      );
    end if;

    select count(*)::integer into v_burst
    from public.matches m
    where lower(coalesce(to_jsonb(m)->>'result_status',''))='confirmed'
      and lower(coalesce(to_jsonb(m)->>'match_type','')) in('ranked','competitive')
      and (m.player1_id=v_player or m.player2_id=v_player)
      and coalesce(
        nullif(to_jsonb(m)->>'confirmed_at','')::timestamptz,
        nullif(to_jsonb(m)->>'created_at','')::timestamptz
      ) between v_occurred-interval '1 hour' and v_occurred+interval '1 second';

    if v_burst>=8 then
      perform public.tt_v77_record_signal(
        v_player,v_opponent,p_match_id,'activity_burst',25,
        jsonb_build_object('ranked_matches_1h',v_burst),v_occurred
      );
    end if;

    v_results:=v_results||jsonb_build_array(
      public.tt_v77_evaluate_user(v_player,p_allow_enforcement)
    );
  end loop;

  return jsonb_build_object('match_id',p_match_id,'evaluations',v_results);
exception when others then
  -- La integridad nunca puede impedir confirmar un partido.
  raise warning 'TT V77 no pudo evaluar partido %: %',p_match_id,sqlerrm;
  return jsonb_build_object('match_id',p_match_id,'error',sqlerrm);
end;
$function$;

create or replace function public.tt_v77_match_moderation_trigger()
returns trigger
language plpgsql
security definer
set search_path=''
as $function$
begin
  if lower(coalesce(to_jsonb(new)->>'result_status',''))<>'confirmed' then
    return new;
  end if;
  if tg_op='INSERT' then
    perform public.tt_v77_evaluate_match(new.id,true);
  elsif lower(coalesce(to_jsonb(old)->>'result_status','')) is distinct from 'confirmed' then
    perform public.tt_v77_evaluate_match(new.id,true);
  end if;
  return new;
exception when others then
  raise warning 'TT V77 trigger omitido para partido %: %',new.id,sqlerrm;
  return new;
end;
$function$;

drop trigger if exists match_auto_moderation_v77 on public.matches;
create trigger match_auto_moderation_v77
after insert or update of result_status on public.matches
for each row
execute function public.tt_v77_match_moderation_trigger();

create or replace function public.admin_get_auto_moderation_v77(p_limit integer default 50)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_admin uuid:=auth.uid();
  v_config jsonb;
  v_cases jsonb;
  v_summary jsonb;
begin
  if not public.tt_v58_is_admin(v_admin) then raise exception 'Solo Administrador'; end if;

  select to_jsonb(c) into v_config
  from tt_private_v77.auto_moderation_config_v77 c
  where c.singleton=true;

  select jsonb_build_object(
    'open_cases',count(*) filter(where c.status in('observed','would_suspend','suspended')),
    'threshold_cases',count(*) filter(where c.status in('would_suspend','suspended')),
    'automatic_suspensions',count(*) filter(where c.status='suspended')
  ) into v_summary
  from public.auto_moderation_cases_v77 c;

  select coalesce(jsonb_agg(to_jsonb(row_data) order by row_data.updated_at desc),'[]'::jsonb)
  into v_cases
  from(
    select
      c.id,c.user_id,c.status,c.score,c.distinct_matches,c.distinct_signal_types,
      c.evaluation_mode,c.suspension_until,c.created_at,c.updated_at,c.review_note,
      p.username,p.first_name,p.last_name,p.profile_photo_url,
      coalesce((
        select jsonb_agg(jsonb_build_object(
          'type',s.signal_type,'points',s.points,'match_id',s.match_id,
          'opponent_id',s.opponent_id,'occurred_at',s.created_at,'evidence',s.evidence
        ) order by s.created_at desc)
        from public.auto_moderation_signals_v77 s
        where s.user_id=c.user_id and s.active
      ),'[]'::jsonb) as signals
    from public.auto_moderation_cases_v77 c
    left join public.profiles p on p.id=c.user_id
    where c.status in('observed','would_suspend','suspended')
    order by c.updated_at desc
    limit greatest(1,least(200,coalesce(p_limit,50)))
  ) row_data;

  return jsonb_build_object('config',v_config,'summary',v_summary,'cases',v_cases);
end;
$function$;

create or replace function public.admin_set_auto_moderation_mode_v77(
  p_mode text,
  p_confirmation text default null
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare v_admin uuid:=auth.uid();
begin
  if not public.tt_v58_is_admin(v_admin) then raise exception 'Solo Administrador'; end if;
  if p_mode not in('observe','enforce','paused') then raise exception 'Modo inválido'; end if;
  if p_mode='enforce' and upper(trim(coalesce(p_confirmation,'')))<>'ACTIVAR' then
    raise exception 'Confirmación requerida para activar suspensiones automáticas';
  end if;

  update tt_private_v77.auto_moderation_config_v77
  set mode=p_mode,updated_by=v_admin,updated_at=now()
  where singleton=true;

  insert into public.auto_moderation_actions_v77(action,mode,details,actor_id)
  values('mode_changed',p_mode,jsonb_build_object('previous_cases_are_not_enforced',true),v_admin);

  return public.admin_get_auto_moderation_v77(50);
end;
$function$;

create or replace function public.admin_dismiss_auto_moderation_case_v77(
  p_case_id bigint,
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_admin uuid:=auth.uid();
  v_user uuid;
begin
  if not public.tt_v58_is_admin(v_admin) then raise exception 'Solo Administrador'; end if;

  update public.auto_moderation_cases_v77
  set status='dismissed',reviewed_by=v_admin,
      review_note=nullif(trim(coalesce(p_note,'')),''),updated_at=now()
  where id=p_case_id and status in('observed','would_suspend')
  returning user_id into v_user;
  if v_user is null then raise exception 'El caso no existe o ya fue resuelto'; end if;

  update public.auto_moderation_signals_v77
  set active=false
  where user_id=v_user and active;

  insert into public.auto_moderation_actions_v77(case_id,user_id,action,mode,details,actor_id)
  values(p_case_id,v_user,'dismissed',null,jsonb_build_object('note',nullif(trim(coalesce(p_note,'')),'')),v_admin);

  return public.admin_get_auto_moderation_v77(50);
end;
$function$;

create or replace function public.admin_reprocess_auto_moderation_v77(
  p_days integer default 7,
  p_limit integer default 500
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_admin uuid:=auth.uid();
  v_days integer:=greatest(1,least(14,coalesce(p_days,7)));
  v_limit integer:=greatest(1,least(1000,coalesce(p_limit,500)));
  v_row record;
  v_count integer:=0;
  v_mode text;
begin
  if not public.tt_v58_is_admin(v_admin) then raise exception 'Solo Administrador'; end if;
  select c.mode into v_mode
  from tt_private_v77.auto_moderation_config_v77 c
  where c.singleton=true;
  if v_mode='paused' then raise exception 'El motor está pausado. Elegí Simulación antes de reanalizar'; end if;

  update public.auto_moderation_signals_v77
  set active=false
  where created_at>=now()-make_interval(days=>v_days);

  for v_row in
    select source.id
    from(
      select m.id,
        coalesce(
          nullif(to_jsonb(m)->>'confirmed_at','')::timestamptz,
          nullif(to_jsonb(m)->>'created_at','')::timestamptz
        ) as occurred_at
      from public.matches m
      where lower(coalesce(to_jsonb(m)->>'result_status',''))='confirmed'
        and lower(coalesce(to_jsonb(m)->>'match_type','')) in('ranked','competitive')
        and coalesce(
          nullif(to_jsonb(m)->>'confirmed_at','')::timestamptz,
          nullif(to_jsonb(m)->>'created_at','')::timestamptz
        )>=now()-make_interval(days=>v_days)
      order by occurred_at desc
      limit v_limit
    ) source
    order by source.occurred_at asc
  loop
    perform public.tt_v77_evaluate_match(v_row.id,false);
    v_count:=v_count+1;
  end loop;

  insert into public.auto_moderation_actions_v77(action,mode,details,actor_id)
  values('simulation_reprocessed','observe',jsonb_build_object('days',v_days,'matches',v_count),v_admin);

  return public.admin_get_auto_moderation_v77(50)||jsonb_build_object('reprocessed_matches',v_count);
end;
$function$;

revoke all on function public.tt_v77_json_number(jsonb,text) from public,anon,authenticated;
revoke all on function public.tt_v77_json_boolean(jsonb,text) from public,anon,authenticated;
revoke all on function public.tt_v77_is_protected_user(uuid) from public,anon,authenticated;
revoke all on function public.tt_v77_pair_has_exception(uuid,uuid) from public,anon,authenticated;
revoke all on function public.tt_v77_record_signal(uuid,uuid,bigint,text,integer,jsonb,timestamptz) from public,anon,authenticated;
revoke all on function public.tt_v77_evaluate_user(uuid,boolean) from public,anon,authenticated;
revoke all on function public.tt_v77_evaluate_match(bigint,boolean) from public,anon,authenticated;
revoke all on function public.tt_v77_match_moderation_trigger() from public,anon,authenticated;

revoke all on function public.admin_get_auto_moderation_v77(integer) from public,anon;
revoke all on function public.admin_set_auto_moderation_mode_v77(text,text) from public,anon;
revoke all on function public.admin_dismiss_auto_moderation_case_v77(bigint,text) from public,anon;
revoke all on function public.admin_reprocess_auto_moderation_v77(integer,integer) from public,anon;
grant execute on function public.admin_get_auto_moderation_v77(integer) to authenticated;
grant execute on function public.admin_set_auto_moderation_mode_v77(text,text) to authenticated;
grant execute on function public.admin_dismiss_auto_moderation_case_v77(bigint,text) to authenticated;
grant execute on function public.admin_reprocess_auto_moderation_v77(integer,integer) to authenticated;

notify pgrst,'reload schema';
commit;

select jsonb_build_object(
  'resultado','P7.4R.4 instalado',
  'modo','observe',
  'suspensiones_reales',false,
  'siguiente_paso','Abrí Admin > Partidos sospechosos y ejecutá Reanalizar 7 días'
) as resultado;
