-- TT Rivals 1.0.1 — P7.4R.3.1
-- Hotfix: restaura el ranking y expulsa en vivo las sesiones baneadas.
-- Requiere P7.4R.2 y P7.4R.3 instalados.

begin;

-- visible_profiles_v76 usa tt_v76_user_is_hidden en cada consulta.
-- El rol autenticado necesita EXECUTE para poder consumir esa vista.
grant execute on function public.tt_v76_user_is_hidden(uuid) to authenticated;

create table if not exists public.access_revocation_events_v76(
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  ban_type text not null,
  source text not null,
  created_at timestamptz not null default now()
);

create index if not exists access_revocation_events_v76_user_date_idx
on public.access_revocation_events_v76(user_id,created_at desc);

alter table public.access_revocation_events_v76 enable row level security;
revoke all on public.access_revocation_events_v76 from public,anon,authenticated;
grant select on public.access_revocation_events_v76 to authenticated;

drop policy if exists access_revocation_events_v76_select_own
on public.access_revocation_events_v76;
create policy access_revocation_events_v76_select_own
on public.access_revocation_events_v76
for select
to authenticated
using(user_id=auth.uid());

create or replace function public.tt_v76_emit_account_revocation()
returns trigger
language plpgsql
security definer
set search_path=''
as $function$
begin
  if new.active then
    insert into public.access_revocation_events_v76(user_id,ban_type,source)
    select coalesce(new.user_id,u.id),new.ban_type,'account'
    from (select 1) seed
    left join lateral(
      select au.id
      from auth.users au
      where public.tt_v75_email_key(au.email)=new.email_key
      order by au.created_at desc
      limit 1
    ) u on true
    where coalesce(new.user_id,u.id) is not null;
  end if;
  return new;
end;
$function$;

create or replace function public.tt_v76_emit_device_revocation()
returns trigger
language plpgsql
security definer
set search_path=''
as $function$
begin
  if new.active then
    insert into public.access_revocation_events_v76(user_id,ban_type,source)
    select distinct ia.user_id,'device_permanent','device'
    from public.installation_accounts_v58 ia
    where ia.installation_id=new.installation_id
      and ia.user_id is not null;
  end if;
  return new;
end;
$function$;

create or replace function public.tt_v76_emit_ip_revocation()
returns trigger
language plpgsql
security definer
set search_path=''
as $function$
begin
  if new.active then
    insert into public.access_revocation_events_v76(user_id,ban_type,source)
    select distinct o.user_id,'ip_permanent','ip'
    from public.access_observations_v75 o
    where o.ip_hash=new.ip_hash
      and o.user_id is not null;
  end if;
  return new;
end;
$function$;

revoke all on function public.tt_v76_emit_account_revocation() from public,anon,authenticated;
revoke all on function public.tt_v76_emit_device_revocation() from public,anon,authenticated;
revoke all on function public.tt_v76_emit_ip_revocation() from public,anon,authenticated;

drop trigger if exists account_access_revocation_v76 on public.account_access_bans_v75;
create trigger account_access_revocation_v76
after insert or update of active on public.account_access_bans_v75
for each row when(new.active)
execute function public.tt_v76_emit_account_revocation();

drop trigger if exists device_access_revocation_v76 on public.device_access_bans_v75;
create trigger device_access_revocation_v76
after insert or update of active on public.device_access_bans_v75
for each row when(new.active)
execute function public.tt_v76_emit_device_revocation();

drop trigger if exists ip_access_revocation_v76 on public.ip_access_bans_v75;
create trigger ip_access_revocation_v76
after insert or update of active on public.ip_access_bans_v75
for each row when(new.active)
execute function public.tt_v76_emit_ip_revocation();

do $block$
begin
  if not exists(
    select 1
    from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='access_revocation_events_v76'
  ) then
    alter publication supabase_realtime
      add table public.access_revocation_events_v76;
  end if;
end;
$block$;

notify pgrst,'reload schema';
commit;

select jsonb_build_object(
  'resultado','P7.4R.3.1 instalado',
  'ranking','restaurado',
  'expulsion_sesiones','realtime + comprobacion de respaldo'
) as resultado;
