-- TT Rivals 1.0.1 — P7.4R.3 Moderación, apelaciones y verificación de correo
-- Requiere P7.4R.2 ya instalado.
-- Esta migración es segura para ejecutar antes de publicar la nueva interfaz.
-- La verificación de correo queda DESACTIVADA en el interruptor interno hasta
-- completar la configuración de Authentication en Supabase.

begin;

create schema if not exists tt_private_v76;
revoke all on schema tt_private_v76 from public,anon,authenticated;

create table if not exists tt_private_v76.registration_config_v76(
  singleton boolean primary key default true check(singleton),
  enabled boolean not null default false,
  otp_minutes integer not null default 10 check(otp_minutes between 2 and 60),
  resend_seconds integer not null default 60 check(resend_seconds between 30 and 600),
  updated_at timestamptz not null default now()
);

insert into tt_private_v76.registration_config_v76(singleton,enabled,otp_minutes,resend_seconds)
values(true,false,10,60)
on conflict(singleton) do nothing;

revoke all on all tables in schema tt_private_v76 from public,anon,authenticated;

create table if not exists public.ban_appeals_v76(
  id bigint generated by default as identity primary key,
  user_id uuid,
  email_key text not null,
  contact_email text not null,
  subject text not null default 'cuenta suspendida',
  message text not null check(char_length(message) between 20 and 2000),
  ban_kind text not null,
  blocked_until timestamptz,
  installation_id uuid,
  ip_hash text,
  status text not null default 'pending'
    check(status in('pending','reviewed','approved','rejected')),
  submitted_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by uuid,
  admin_note text
);

create unique index if not exists ban_appeals_v76_one_pending_email_idx
on public.ban_appeals_v76(email_key)
where status='pending';

create index if not exists ban_appeals_v76_status_date_idx
on public.ban_appeals_v76(status,submitted_at desc);

alter table public.ban_appeals_v76 enable row level security;
revoke all on public.ban_appeals_v76 from public,anon,authenticated;

create or replace function public.tt_v76_user_is_hidden(p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path=''
as $function$
  select exists(
    select 1
    from auth.users u
    where u.id=p_user_id
      and (
        exists(
          select 1
          from public.account_access_bans_v75 b
          where b.active
            and (
              b.user_id=u.id
              or b.email_key=public.tt_v75_email_key(u.email)
            )
            and (
              b.ban_type='email_permanent'
              or (b.ban_type='temporary' and b.blocked_until>now())
            )
        )
        or exists(
          select 1
          from public.device_access_bans_v75 d
          where d.active
            and (
              d.source_user_id=u.id
              or exists(
                select 1
                from public.installation_accounts_v58 ia
                where ia.user_id=u.id
                  and ia.installation_id=d.installation_id
              )
            )
        )
        or exists(
          select 1
          from public.ip_access_bans_v75 ib
          where ib.active
            and (
              ib.source_user_id=u.id
              or exists(
                select 1
                from public.access_observations_v75 o
                where o.user_id=u.id
                  and o.ip_hash=ib.ip_hash
              )
            )
        )
      )
  );
$function$;

revoke all on function public.tt_v76_user_is_hidden(uuid) from public,anon,authenticated;

-- Conserva el hook ya activado en Supabase y añade unicidad canónica de correo.
-- Para Gmail también bloquea variantes con puntos o sufijos +alias.
create or replace function public.hook_before_user_created_v75(event jsonb)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_user_id uuid:=(event->'user'->>'id')::uuid;
  v_email text:=event->'user'->>'email';
  v_email_key text:=public.tt_v75_email_key(event->'user'->>'email');
  v_installation uuid;
  v_ip text:=event->'metadata'->>'ip_address';
  v_decision jsonb;
begin
  begin
    v_installation:=nullif(event->'user'->'user_metadata'->>'installation_id','')::uuid;
  exception when others then
    v_installation:=null;
  end;

  v_decision:=public.tt_v75_access_decision(v_email,v_installation,v_user_id,v_ip,false,'signup');
  if not coalesce((v_decision->>'allowed')::boolean,false) then
    return jsonb_build_object('error',jsonb_build_object(
      'http_code',403,
      'message',v_decision->>'message'
    ));
  end if;

  delete from auth.users u
  where u.id<>v_user_id
    and u.email_confirmed_at is null
    and u.created_at<now()-interval '7 days'
    and public.tt_v75_email_key(u.email)=v_email_key;

  if exists(
    select 1
    from auth.users u
    where u.id<>v_user_id
      and public.tt_v75_email_key(u.email)=v_email_key
  ) then
    return jsonb_build_object('error',jsonb_build_object(
      'http_code',400,
      'message','Ese correo ya está registrado o no puede utilizarse'
    ));
  end if;

  perform public.tt_v75_access_decision(v_email,v_installation,v_user_id,v_ip,true,'signup');
  return '{}'::jsonb;
end;
$function$;

revoke all on function public.hook_before_user_created_v75(jsonb) from public,anon,authenticated;
grant execute on function public.hook_before_user_created_v75(jsonb) to supabase_auth_admin;

drop view if exists public.visible_profiles_v76;
create view public.visible_profiles_v76
with(security_barrier=true)
as
select p.*
from public.profiles p
where not public.tt_v76_user_is_hidden(p.id);

revoke all on public.visible_profiles_v76 from public;
grant select on public.visible_profiles_v76 to anon,authenticated;

create or replace function public.filter_visible_user_ids_v76(p_user_ids uuid[])
returns table(user_id uuid)
language sql
stable
security definer
set search_path=''
as $function$
  select distinct x.user_id
  from unnest(coalesce(p_user_ids,'{}'::uuid[])) as x(user_id)
  where x.user_id is not null
    and not public.tt_v76_user_is_hidden(x.user_id)
  limit 500;
$function$;

revoke all on function public.filter_visible_user_ids_v76(uuid[]) from public;
grant execute on function public.filter_visible_user_ids_v76(uuid[]) to anon,authenticated;

create or replace function public.get_registration_config_v76()
returns jsonb
language sql
stable
security definer
set search_path=''
as $function$
  select jsonb_build_object(
    'enabled',c.enabled,
    'otp_minutes',c.otp_minutes,
    'resend_seconds',c.resend_seconds
  )
  from tt_private_v76.registration_config_v76 c
  where c.singleton;
$function$;

revoke all on function public.get_registration_config_v76() from public;
grant execute on function public.get_registration_config_v76() to anon,authenticated;

create or replace function public.cancel_unverified_signup_v76(
  p_user_id uuid,
  p_cancel_token text
)
returns boolean
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_user auth.users%rowtype;
  v_profile_completed boolean:=false;
begin
  if p_user_id is null
    or char_length(coalesce(p_cancel_token,''))<32
    or char_length(coalesce(p_cancel_token,''))>200 then
    raise exception 'No se pudo validar el registro pendiente';
  end if;

  select * into v_user
  from auth.users
  where id=p_user_id
  for update;

  if not found then return true; end if;
  if v_user.created_at<now()-interval '7 days' then
    raise exception 'El registro pendiente ya no puede modificarse';
  end if;
  if coalesce(v_user.raw_user_meta_data->>'registration_cancel_token','')<>p_cancel_token then
    raise exception 'No se pudo validar el registro pendiente';
  end if;

  select coalesce(p.profile_completed,false) into v_profile_completed
  from public.profiles p
  where p.id=p_user_id;

  if v_user.email_confirmed_at is not null
    and (v_user.created_at<now()-interval '10 minutes' or coalesce(v_profile_completed,false)) then
    raise exception 'El correo ya fue verificado';
  end if;

  delete from auth.sessions where user_id=p_user_id;
  delete from public.access_observations_v75 where user_id=p_user_id;
  delete from auth.users where id=p_user_id;
  return true;
end;
$function$;

revoke all on function public.cancel_unverified_signup_v76(uuid,text) from public;
grant execute on function public.cancel_unverified_signup_v76(uuid,text) to anon,authenticated;

create or replace function public.submit_ban_appeal_v76(
  p_email text,
  p_message text,
  p_installation_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_email text:=lower(trim(coalesce(p_email,'')));
  v_key text;
  v_message text:=trim(coalesce(p_message,''));
  v_user_id uuid;
  v_ip_hash text:=public.tt_v75_ip_hash(public.tt_v75_request_ip());
  v_decision jsonb;
  v_existing bigint;
  v_id bigint;
begin
  if v_email!~*'^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$'
    or char_length(v_email)>320 then
    raise exception 'Ingresá un correo válido';
  end if;
  if char_length(v_message)<20 then
    raise exception 'Contanos lo ocurrido en al menos 20 caracteres';
  end if;
  if char_length(v_message)>2000 then
    raise exception 'La apelación no puede superar los 2000 caracteres';
  end if;

  v_key:=public.tt_v75_email_key(v_email);
  select u.id into v_user_id
  from auth.users u
  where public.tt_v75_email_key(u.email)=v_key
  order by u.created_at desc
  limit 1;

  v_decision:=public.tt_v75_access_decision(
    v_email,p_installation_id,v_user_id,public.tt_v75_request_ip(),false,'session'
  );
  if coalesce((v_decision->>'allowed')::boolean,true) then
    raise exception 'No encontramos una suspensión activa para estos datos';
  end if;

  select a.id into v_existing
  from public.ban_appeals_v76 a
  where a.email_key=v_key and a.status='pending'
  order by a.submitted_at desc
  limit 1;

  if v_existing is not null then
    return jsonb_build_object(
      'ok',true,'already_pending',true,'appeal_id',v_existing,
      'email_to','ttrivalsuy@gmail.com','subject','cuenta suspendida'
    );
  end if;

  insert into public.ban_appeals_v76(
    user_id,email_key,contact_email,message,ban_kind,blocked_until,
    installation_id,ip_hash
  )
  values(
    v_user_id,v_key,v_email,v_message,coalesce(v_decision->>'kind','unknown'),
    nullif(v_decision->>'until','')::timestamptz,p_installation_id,v_ip_hash
  )
  returning id into v_id;

  return jsonb_build_object(
    'ok',true,'already_pending',false,'appeal_id',v_id,
    'email_to','ttrivalsuy@gmail.com','subject','cuenta suspendida'
  );
end;
$function$;

revoke all on function public.submit_ban_appeal_v76(text,text,uuid) from public;
grant execute on function public.submit_ban_appeal_v76(text,text,uuid) to anon,authenticated;

create or replace function public.admin_list_suspended_users_v76()
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_users jsonb;
  v_appeals integer;
begin
  if not public.tt_v58_is_admin(auth.uid()) then raise exception 'Solo Administrador'; end if;

  select coalesce(jsonb_agg(q.item order by q.last_activity desc),'[]'::jsonb)
  into v_users
  from(
    select
      greatest(
        coalesce((
          select max(b.created_at) from public.account_access_bans_v75 b
          where b.active and (b.user_id=u.id or b.email_key=public.tt_v75_email_key(u.email))
        ),'-infinity'::timestamptz),
        coalesce((select max(d.created_at) from public.device_access_bans_v75 d where d.active and d.source_user_id=u.id),'-infinity'::timestamptz),
        coalesce((select max(i.created_at) from public.ip_access_bans_v75 i where i.active and i.source_user_id=u.id),'-infinity'::timestamptz)
      ) as last_activity,
      jsonb_build_object(
        'user_id',u.id,
        'email',u.email,
        'username',p.username,
        'first_name',p.first_name,
        'last_name',p.last_name,
        'profile_photo_url',p.profile_photo_url,
        'account_ban',(
          select jsonb_build_object(
            'type',b.ban_type,'until',b.blocked_until,'created_at',b.created_at
          )
          from public.account_access_bans_v75 b
          where b.active
            and (b.user_id=u.id or b.email_key=public.tt_v75_email_key(u.email))
            and (
              b.ban_type='email_permanent'
              or (b.ban_type='temporary' and b.blocked_until>now())
            )
          order by b.created_at desc limit 1
        ),
        'device_bans',(
          select count(*) from public.device_access_bans_v75 d
          where d.active and d.source_user_id=u.id
        ),
        'ip_bans',(
          select count(*) from public.ip_access_bans_v75 i
          where i.active and i.source_user_id=u.id
        ),
        'pending_appeals',(
          select count(*) from public.ban_appeals_v76 a
          where a.status='pending'
            and (a.user_id=u.id or a.email_key=public.tt_v75_email_key(u.email))
        ),
        'latest_appeal',(
          select jsonb_build_object(
            'id',a.id,'message',a.message,'status',a.status,
            'submitted_at',a.submitted_at,'ban_kind',a.ban_kind
          )
          from public.ban_appeals_v76 a
          where a.user_id=u.id or a.email_key=public.tt_v75_email_key(u.email)
          order by a.submitted_at desc limit 1
        )
      ) as item
    from auth.users u
    left join public.profiles p on p.id=u.id
    where public.tt_v76_user_is_hidden(u.id)
  ) q;

  select count(*) into v_appeals
  from public.ban_appeals_v76
  where status='pending';

  return jsonb_build_object(
    'users',v_users,
    'total',jsonb_array_length(v_users),
    'pending_appeals',v_appeals
  );
end;
$function$;

create or replace function public.admin_resolve_ban_appeal_v76(
  p_appeal_id bigint,
  p_decision text,
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_admin uuid:=auth.uid();
  v_appeal public.ban_appeals_v76%rowtype;
begin
  if not public.tt_v58_is_admin(v_admin) then raise exception 'Solo Administrador'; end if;
  if p_decision not in('approved','rejected','reviewed') then
    raise exception 'Decisión inválida';
  end if;

  select * into v_appeal
  from public.ban_appeals_v76
  where id=p_appeal_id
  for update;
  if not found then raise exception 'Apelación no encontrada'; end if;

  if p_decision='approved' then
    update public.account_access_bans_v75
      set active=false,revoked_by=v_admin,revoked_at=now()
      where active
        and (user_id=v_appeal.user_id or email_key=v_appeal.email_key);

    update public.device_access_bans_v75
      set active=false,revoked_by=v_admin,revoked_at=now()
      where active
        and (
          source_user_id=v_appeal.user_id
          or installation_id=v_appeal.installation_id
        );

    update public.ip_access_bans_v75
      set active=false,revoked_by=v_admin,revoked_at=now()
      where active
        and (
          source_user_id=v_appeal.user_id
          or ip_hash=v_appeal.ip_hash
        );

    if v_appeal.user_id is not null then
      update auth.users set banned_until=null where id=v_appeal.user_id;
    end if;
  end if;

  update public.ban_appeals_v76
  set status=p_decision,resolved_at=now(),resolved_by=v_admin,
      admin_note=nullif(trim(coalesce(p_note,'')),'')
  where id=p_appeal_id;

  insert into public.access_ban_audit_v75(
    target_user_id,admin_id,action,ban_type,affected_items,note
  )
  select
    v_appeal.user_id,v_admin,
    case when p_decision='approved' then 'appeal_approved' else 'appeal_'||p_decision end,
    v_appeal.ban_kind,0,nullif(trim(coalesce(p_note,'')),'')
  where v_appeal.user_id is not null;

  return public.admin_list_suspended_users_v76();
end;
$function$;

revoke all on function public.admin_list_suspended_users_v76() from public,anon;
revoke all on function public.admin_resolve_ban_appeal_v76(bigint,text,text) from public,anon;
grant execute on function public.admin_list_suspended_users_v76() to authenticated;
grant execute on function public.admin_resolve_ban_appeal_v76(bigint,text,text) to authenticated;

notify pgrst,'reload schema';
commit;

select jsonb_build_object(
  'resultado','P7.4R.3 instalado',
  'verificacion_email_activa',false,
  'siguiente_paso','Configurar Confirm email, plantilla OTP y SMTP antes de activar el interruptor'
) as resultado;

-- ACTIVACIÓN FINAL (ejecutar solamente después de configurar Authentication
-- y después de publicar la interfaz P7.4R.3):
--
-- update tt_private_v76.registration_config_v76
-- set enabled=true,otp_minutes=10,resend_seconds=60,updated_at=now()
-- where singleton;


